# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import json
import time
import random
import threading
import traceback
import difflib
import http.client
import urllib.request
import urllib.error
import urllib.parse
import os
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional, Any
from dataclasses import dataclass, field
from v4_modules.utils import safe_print, C, log, TokenBucket, cache_tool_output
from v4_modules.config import (AccountConfig, PortContext, build_port_context, render_port_context,
                                GEMINI_API_BASE)
from v4_modules.rag import LongTermMemory, SessionRAG, ProjectRAG, _fmt_msg_for_summary
from v4_modules.autogit import AutoGit, ReactLog
from v4_modules.tools import ToolRegistry, clear_read_files_registry


# ── ProjectRAG 共有キャッシュ ────────────────────────────────
_shared_project_rag_cache: dict[str, ProjectRAG] = {}
_shared_project_rag_lock = threading.Lock()

def get_shared_project_rag(cwd: str) -> ProjectRAG:
    """ディレクトリごとに単一の ProjectRAG インスタンスを返す（永続化対応）"""
    abs_cwd = str(Path(cwd).resolve())
    with _shared_project_rag_lock:
        if abs_cwd not in _shared_project_rag_cache:
            rag = ProjectRAG()
            if rag.load(abs_cwd):
                safe_print(C.gray(f"  [ProjectRAG] 既存のインデックスをロードしました: {rag.chunk_count}チャンク"))
            _shared_project_rag_cache[abs_cwd] = rag
        return _shared_project_rag_cache[abs_cwd]

class GeminiAPIError(Exception):
    def __init__(self, status: int, message: str):
        self.status = status
        self.message = message
        super().__init__(f"HTTP {status}: {message}")

class RateLimitError(GeminiAPIError):
    pass

class ServerError(GeminiAPIError):
    pass

def _to_gemini_contents(messages: list[dict]) -> list[dict]:
    """
    内部メッセージ形式を Gemini API の contents 形式に変換する。

    内部形式:
      {"role": "user",      "content": "text"}
      {"role": "assistant", "content": "thought", "function_calls": [{"name":..,"args":..}]}
      {"role": "user",      "content": "",        "function_results": [{"name":..,"result":..}]}

    Gemini API 形式:
      {"role": "user",  "parts": [{"text": "..."}]}
      {"role": "model", "parts": [{"text": "..."}, {"functionCall": {...}}]}
      {"role": "user",  "parts": [{"functionResponse": {"name":..,"response":{"result":..}}}]}
    """
    contents = []
    for m in messages:
        role = m.get("role", "user")
        gemini_role = "user" if role == "user" else "model"

        if m.get("function_results"):
            # functionResponse メッセージ（ツール結果）
            parts = [
                {
                    "functionResponse": {
                        "name": r["name"],
                        "response": {"result": r["result"]}
                    }
                }
                for r in m["function_results"]
            ]
            contents.append({"role": "user", "parts": parts})

        elif m.get("function_calls") and role == "assistant":
            # functionCall を含むモデルの応答
            parts: list[dict] = []
            if m.get("content"):
                parts.append({"text": m["content"]})
            parts += [
                {"functionCall": {"name": fc["name"], "args": fc.get("args", {})}}
                for fc in m["function_calls"]
            ]
            contents.append({"role": "model", "parts": parts})

        else:
            content_text = str(m.get("content", ""))
            if content_text:
                contents.append({"role": gemini_role, "parts": [{"text": content_text}]})

    return contents

def _msg_char_count(m: dict) -> int:
    """メッセージの文字数を返す（function_results も含む）"""
    count = len(str(m.get("content", "")))
    for r in m.get("function_results", []):
        count += len(str(r.get("result", "")))
    for fc in m.get("function_calls", []):
        count += len(str(fc.get("args", "")))
    return count

def _trim_messages_smart(messages: list[dict]) -> list[dict]:
    """
    ペイロード削減のためにメッセージを賢くトリムする。

    優先削除順（重要度が低いものから）:
      1. ツール結果メッセージ（function_results または [ツール: で始まるもの）の古い順
      2. それでも足りなければ古い順に均等削除（先頭2件は保護）

    1回の呼び出しで約25%削減を目標とする。
    """
    protected = messages[:2]
    body = messages[2:]

    if not body:
        return messages

    target_remove = max(2, len(body) // 4)

    # ① ツール結果メッセージを古い順に探して削除候補とする
    tool_indices = [
        i for i, m in enumerate(body)
        if m.get("role") == "user" and (
            bool(m.get("function_results")) or
            str(m.get("content", "")).startswith("[ツール:")
        )
    ]

    removed = 0
    indices_to_remove: set[int] = set()

    for idx in tool_indices:
        if removed >= target_remove:
            break
        indices_to_remove.add(idx)
        removed += 1
        # 直前のassistantメッセージがfunctionCallなら一緒に削除（孤立functionCall防止）
        if idx > 0 and body[idx - 1].get("function_calls") and idx - 1 not in indices_to_remove:
            indices_to_remove.add(idx - 1)

    # ② ツール結果だけでは足りない場合は古い順に追加削除
    if removed < target_remove:
        for i in range(len(body)):
            if removed >= target_remove:
                break
            if i not in indices_to_remove:
                # functionCallメッセージを単独削除しないよう、次がfunction_resultsなら一緒に削除
                indices_to_remove.add(i)
                removed += 1
                if (body[i].get("function_calls")
                        and i + 1 < len(body)
                        and body[i + 1].get("function_results")
                        and i + 1 not in indices_to_remove):
                    indices_to_remove.add(i + 1)

    trimmed_body = [m for i, m in enumerate(body) if i not in indices_to_remove]
    return protected + trimmed_body

def _repair_message_sequence(messages: list[dict]) -> list[dict]:
    """
    Geminiに送る前にメッセージ列の整合性を修復する。
    孤立したfunctionCall（対応するfunctionResponseがない）を削除し、
    user→model→user の交互順序を保証する。
    """
    repaired = []
    for i, m in enumerate(messages):
        if m.get("function_calls"):
            # 次のメッセージがfunction_resultsでなければ孤立 → 削除
            next_m = messages[i + 1] if i + 1 < len(messages) else None
            if next_m is None or not next_m.get("function_results"):
                log.warning({"event": "orphan_function_call_removed",
                             "index": i, "calls": [fc["name"] for fc in m["function_calls"]]})
                continue
        if m.get("function_results"):
            # 直前のメッセージがfunction_callsでなければ孤立 → 削除
            prev_m = repaired[-1] if repaired else None
            if prev_m is None or not prev_m.get("function_calls"):
                log.warning({"event": "orphan_function_results_removed", "index": i})
                continue
        repaired.append(m)
    return repaired

def _build_gemini_payload(
    account: AccountConfig,
    messages: list[dict],
    tool_specs: list[dict],
    system_prompt: Optional[str],
    json_mode: bool,
) -> dict:
    """_call_gemini_api / _stream_gemini_api 共通のリクエストペイロードを構築する。"""
    contents = _to_gemini_contents(messages)
    payload: dict[str, Any] = {"contents": contents}

    if system_prompt:
        payload["system_instruction"] = {"parts": [{"text": system_prompt}]}

    # Gemma 4 は thinkingBudget 非対応。Gemini 2.5+ は対応。モデル名で自動判別。
    gen_config: dict[str, Any] = {}
    if "gemini-2.5" in account.model or "gemini-3" in account.model:
        budget_map = {"HIGH": -1, "MEDIUM": 8192, "LOW": 1024, "NONE": 0}
        budget = budget_map.get(account.thinking_level.upper(), -1)
        if budget != 0:
            gen_config["thinkingConfig"] = {"thinkingBudget": budget}
    if json_mode:
        gen_config["response_mime_type"] = "application/json"
    if gen_config:
        payload["generationConfig"] = gen_config

    if tool_specs:
        payload["tools"] = [{"functionDeclarations": tool_specs}]
        payload["toolConfig"] = {"functionCallingConfig": {"mode": "AUTO"}}

    return payload


def _call_gemini_api(account: AccountConfig, messages: list[dict],
                     tool_specs: list[dict],
                     system_prompt: Optional[str] = None,
                     json_mode: bool = False) -> dict:
    """Gemini API を直接呼び出す（urllib のみ使用）"""
    url = f"{GEMINI_API_BASE}/{account.model}:generateContent?key={account.api_key}"
    payload = _build_gemini_payload(account, messages, tool_specs, system_prompt, json_mode)
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body_text = e.read().decode("utf-8", errors="replace")
        try:
            err_json = json.loads(body_text)
            msg = err_json.get("error", {}).get("message", body_text)
        except Exception:
            msg = body_text
        if e.code == 429:
            raise RateLimitError(e.code, msg)
        if e.code >= 500:
            raise ServerError(e.code, msg)
        raise GeminiAPIError(e.code, msg)
    except urllib.error.URLError as e:
        raise GeminiAPIError(0, f"ネットワークエラー: {e.reason}")

def _stream_gemini_api(account: AccountConfig, messages: list[dict],
                       tool_specs: list[dict],
                       system_prompt: Optional[str] = None,
                       json_mode: bool = False):
    """
    streamGenerateContent SSE エンドポイントでストリーミング呼び出し。

    yields (text_chunk: str, tool_calls: list[dict], finish_reason: str)
      text_chunk   : テキストのかたまり（空文字の場合あり）
      tool_calls   : functionCall が含まれるチャンクのみ非空リスト
      finish_reason: 最終チャンクでのみ非空文字列
    """
    url = (f"{GEMINI_API_BASE}/{account.model}"
           f":streamGenerateContent?alt=sse&key={account.api_key}")

    payload = _build_gemini_payload(account, messages, tool_specs, system_prompt, json_mode)
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req  = urllib.request.Request(
        url, data=body,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=180) as resp:
            for raw_line in resp:
                line = raw_line.decode("utf-8").rstrip("\n\r")
                if not line.startswith("data: "):
                    continue
                data_str = line[6:]
                if not data_str or data_str == "[DONE]":
                    continue
                try:
                    chunk = json.loads(data_str)
                except json.JSONDecodeError:
                    continue

                candidates = chunk.get("candidates", [])
                if not candidates:
                    continue
                candidate     = candidates[0]
                parts         = candidate.get("content", {}).get("parts", [])
                finish_reason = candidate.get("finishReason", "")

                text_chunk = ""
                chunk_tools: list[dict] = []
                for part in parts:
                    if "text" in part:
                        text_chunk += part["text"]
                    elif "functionCall" in part:
                        fc = part["functionCall"]
                        chunk_tools.append({"name": fc["name"],
                                            "args": fc.get("args", {})})

                yield text_chunk, chunk_tools, finish_reason

    except urllib.error.HTTPError as e:
        body_text = e.read().decode("utf-8", errors="replace")
        try:
            msg = json.loads(body_text).get("error", {}).get("message", body_text)
        except Exception:
            msg = body_text
        if e.code == 429:
            raise RateLimitError(e.code, msg)
        if e.code >= 500:
            raise ServerError(e.code, msg)
        raise GeminiAPIError(e.code, msg)
    except urllib.error.URLError as e:
        raise GeminiAPIError(0, f"ネットワークエラー: {e.reason}")

class AccountRotator:
    """
    3アカウントを Token Bucket で管理し、最適なアカウントを選択。

    選択戦略（優先順）:
      1. すぐ使えるアカウント（トークンあり + RPD残あり）→ RPD残量最大を優先
      2. 少し待てば使えるアカウント（RPM待ち最短）
      3. 全アカウント RPD 枯渇 → RuntimeError

    Token Bucket の恩恵:
      - acquire() が O(1) で wait 秒数を返すのでロック競合を最小化
      - 補充が連続的なので「ウィンドウ境界でバーストが2倍」問題が起きない
      - 429受信時は外部バックオフ後に再 acquire → 自然にレート調整
    """

    def __init__(self, accounts: list[AccountConfig]):
        self.accounts = accounts
        self._lock = threading.Lock()

    def pick(self) -> tuple[AccountConfig, float]:
        """
        最適なアカウントを選んで (account, wait_sec) を返す。

        ローテーション戦略（均等分散）:
          1. wait_time() でトークン消費せずに状態を確認
          2. 即利用可能なアカウントから RPD残量が均等になるよう選択
          3. 全アカウント RPM 待ちなら待ち時間最短を選択
          4. acquire() は選んだ1アカウントのみに実行（多重消費なし）
        """
        with self._lock:
            ready: list[AccountConfig] = []
            waiting: list[tuple[AccountConfig, float]] = []

            for acc in self.accounts:
                # wait_time() はトークンを消費しない（参照のみ）
                if acc.bucket.rpd_remaining == 0 and not acc.bucket.rpd_unlimited:
                    continue  # RPD 枯渇: スキップ
                wait = acc.bucket.wait_time()
                if wait == 0.0:
                    ready.append(acc)
                else:
                    waiting.append((acc, wait))

            if ready:
                # RPD 無制限アカウントは使用回数で均等化、有制限はRPD残量で均等化
                ready.sort(key=lambda a: (
                    a.bucket._rpd_count if a.bucket.rpd_unlimited
                    else -a.bucket.rpd_remaining
                ))
                selected = ready[0]
                # 選んだアカウントのみ acquire
                ok, wait = selected.bucket.acquire()
                if ok:
                    return selected, 0.0
                # ごく稀にトークンが枯渇した場合は待ちとして返す
                return selected, wait

            if waiting:
                waiting.sort(key=lambda x: x[1])
                return waiting[0]

            raise RuntimeError(
                "全アカウントが本日の RPD 上限に達しました。明日 UTC 00:00 にリセットされます。"
            )

    def record(self, account: AccountConfig):
        """waiting から選ばれたアカウントの acquire（wait 後に呼ぶ）"""
        account.bucket.acquire()

    # ── Plan-and-Execute サポート ──────────────────────────────

    def total_tokens(self) -> float:
        """全アカウントの利用可能トークン合計（消費ゼロ・参照のみ）"""
        return sum(acc.bucket.tokens_available for acc in self.accounts)

    def can_afford_reviewer(self) -> bool:
        """
        Reviewer を呼べるか判定（消費ゼロ）。
        RPD 無制限モード（GEMINI_RPD=0）では常に True を返す。
        有制限モードでは RPM トークン残量 >= 2.0 を条件とする。
        """
        if all(acc.bucket.rpd_unlimited for acc in self.accounts):
            return True  # RPD無制限: Reviewer/Reflector を常時有効化
        return self.total_tokens() >= 2.0

    def wait_to_start(self, step_count: int) -> float:
        """
        タスク開始に必要な待ち時間を秒で返す。
        必要コール数 = Planner(1) + (Executor(1) + Reviewer(1)) * steps
        """
        needed = float(1 + step_count * 2)
        available = self.total_tokens()
        if available >= needed:
            return 0.0
        total_refill = sum(acc.bucket._refill_rate for acc in self.accounts)
        if total_refill <= 0:
            return 0.0
        return (needed - available) / total_refill

    def status(self) -> list[dict]:
        return [
            {
                "name": acc.name,
                "model": acc.model,
                "rpd_remaining": acc.bucket.rpd_remaining,
                "rpd_unlimited": acc.bucket.rpd_unlimited,
                "tokens_available": round(acc.bucket.tokens_available, 2),
                "rpm_limit": acc.bucket.rpm_limit,
            }
            for acc in self.accounts
        ]

MAX_RETRIES = 5

BASE_BACKOFF = 2.0       # 秒

MAX_BACKOFF = 120.0      # 秒

MAX_TOOL_ROUNDS = 50     # 1ターンあたりのツール呼び出し上限（RPD無制限のため拡大）


_CACHEABLE_TOOLS = frozenset({"read_file", "list_directory", "glob", "grep", "fetch_webpage"})

def _print_write_diff(fn_name: str, fn_args: dict) -> None:
    """
    edit_file / write_file 実行前に変更差分を端末に表示する。
    plan モードでは情報表示のみ（承認なし）。
    react モードの承認フローは InteractiveOrchestrator._confirm_write_tool が担う。
    """
    if fn_name == "edit_file":
        path      = fn_args.get("path", "?")
        old_str   = fn_args.get("old_string", "")
        new_str   = fn_args.get("new_string", "")
        old_lines = old_str.splitlines(keepends=True)
        new_lines = new_str.splitlines(keepends=True)
        diff = list(difflib.unified_diff(
            old_lines, new_lines,
            fromfile=f"a/{path}", tofile=f"b/{path}", lineterm=""
        ))
        if not diff:
            return
        safe_print(C.gray(f"  [diff] {path}"), flush=True)
        for line in diff:
            if line.startswith("+++") or line.startswith("---"):
                safe_print(C.gray(f"    {line}"), end="", flush=True)
            elif line.startswith("+"):
                safe_print(C.green(f"    {line}"), end="", flush=True)
            elif line.startswith("-"):
                safe_print(C.red(f"    {line}"), end="", flush=True)
            else:
                safe_print(C.dim(f"    {line}"), end="", flush=True)
        safe_print(flush=True)

    elif fn_name == "write_file":
        path    = fn_args.get("path", "?")
        content = fn_args.get("content", "")
        p = Path(path)
        if p.exists():
            old_lines = p.read_text(encoding="utf-8", errors="replace").splitlines(keepends=True)
            new_lines = content.splitlines(keepends=True)
            diff = list(difflib.unified_diff(
                old_lines, new_lines,
                fromfile=f"a/{path}", tofile=f"b/{path}", lineterm=""
            ))
            if not diff:
                return
            safe_print(C.gray(f"  [diff] {path}"), flush=True)
            for line in diff:
                if line.startswith("+++") or line.startswith("---"):
                    safe_print(C.gray(f"    {line}"), end="", flush=True)
                elif line.startswith("+"):
                    safe_print(C.green(f"    {line}"), end="", flush=True)
                elif line.startswith("-"):
                    safe_print(C.red(f"    {line}"), end="", flush=True)
                else:
                    safe_print(C.dim(f"    {line}"), end="", flush=True)
            safe_print(flush=True)
        else:
            lines = content.splitlines()
            preview = "\n".join(f"    {C.green('+ ' + l)}" for l in lines[:20])
            suffix  = C.gray(f"\n    ... (+{len(lines) - 20}行)") if len(lines) > 20 else ""
            safe_print(C.gray(f"  [新規ファイル] {path}") + f"\n{preview}{suffix}", flush=True)

class GeminiAgent:
    """
    claw-code スタイルの エージェントループ:
      user → [API call] → tool calls → [API call] → ... → final answer
    """

    # セッション圧縮: 会話の総文字数がこの値を超えたら AI 要約で圧縮
    # メッセージ数ではなくバイト数ベースで判定（大きいツール出力を確実に捕捉）
    COMPACTION_THRESHOLD_CHARS = 500_000  # 50万文字 ≈ 約125kトークン相当
    # 要約後に保持する直近メッセージ数（以前: 8 → 現在: 20 = 10往復）
    COMPACTION_KEEP_RECENT = 20

    def __init__(self, rotator: AccountRotator, tool_registry: ToolRegistry):
        self.rotator = rotator
        self.tools = tool_registry
        self.conversation: list[dict] = []
        self.system_prompt: Optional[str] = None
        self.thinking_enabled: bool = True   # /think on|off で切替
        self.cwd: str = str(Path.cwd().resolve())  # カレントフォルダ追跡
        self._task_goal: Optional[str] = None  # 現在のタスクゴール
        self._tool_cache: dict[str, str] = {}  # 読み取り系ツールのセッション内キャッシュ
        self._tool_cache_lock = threading.Lock()  # 並列ツール実行時の競合防止
        self.json_mode: bool = False  # True のとき API に response_mime_type: application/json を指定
        self._session_rag: Optional[SessionRAG] = None  # 圧縮済み会話のRAGストア
        self._project_rag: Optional[ProjectRAG] = get_shared_project_rag(self.cwd)  # 共有RAG

    def set_system_prompt(self, prompt: str):
        self.system_prompt = prompt

    def set_thinking(self, enabled: bool, silent: bool = False):
        self.thinking_enabled = enabled
        if not silent:
            state = "ON" if enabled else "OFF"
            safe_print(f"  推論モード: {state}")

    # ────────────────────────────────────────────
    # カレントフォルダ認識（1行のみ・毎回スキャンしない）
    # ────────────────────────────────────────────
    def _build_context_header(self) -> str:
        return f"[作業フォルダ] {self.cwd}"

    def set_cwd(self, path: str):
        self.cwd = path
        safe_print(f"  作業フォルダを変更: {path}")

    # ────────────────────────────────────────────
    # ② タスク管理
    # ────────────────────────────────────────────
    def start_task(self, goal: str):
        """複数ステップにまたがるタスクを開始"""
        self._task_goal = goal
        log.info({"event": "task_start", "goal": goal[:80]})

    def end_task(self):
        self._task_goal = None

    def _task_context(self) -> str:
        """タスク進行中の場合、ゴールをコンテキストに注入"""
        if not self._task_goal:
            return ""
        return f"[現在のタスク] {self._task_goal}"

    # ────────────────────────────────────────────
    # ③ セッション圧縮
    # ────────────────────────────────────────────
    def _compact_if_needed(self):
        """
        会話の総文字数が COMPACTION_THRESHOLD_CHARS を超えたら SessionRAG にアーカイブして圧縮する。
        従来のAI要約（情報損失あり）の代わりにベクトルストアへ退避し、
        次ターン以降のクエリで関連部分だけを自動検索・注入する。

        保護ルール:
          - conversation[0:2] (最初の指示と応答) は常に保持
          - アーカイブ対象を SessionRAG に追加
          - 直近 COMPACTION_KEEP_RECENT 件はそのまま保持
        """
        total_chars = sum(_msg_char_count(m) for m in self.conversation)
        if total_chars <= self.COMPACTION_THRESHOLD_CHARS:
            return

        keep_recent = self.COMPACTION_KEEP_RECENT
        first_pair = self.conversation[:2]
        boundary = len(self.conversation) - keep_recent
        to_archive = self.conversation[2:boundary]
        recent_part = self.conversation[boundary:]

        if not to_archive:
            return

        # SessionRAG を初期化（初回のみ）してアーカイブ
        if self._session_rag is None:
            self._session_rag = SessionRAG()

        api_key = self.rotator.pick()[0].api_key
        safe_print(C.gray(
            f"  [SessionRAG] {len(to_archive)}件 / {total_chars:,}文字をRAGストアにアーカイブ中..."
        ), flush=True)
        self._session_rag.store_messages(to_archive, api_key)

        archive_note = {
            "role": "user",
            "content": (
                f"[{len(to_archive)}件の会話をSessionRAGにアーカイブしました。"
                f"累計{self._session_rag.chunk_count}チャンク保存済み。"
                f"関連情報は次のターンで自動検索されます]"
            )
        }
        archive_ack = {
            "role": "assistant",
            "content": "了解しました。必要な情報はセッション記憶から検索して対応します。"
        }

        self.conversation = first_pair + [archive_note, archive_ack] + recent_part
        after_chars = sum(_msg_char_count(m) for m in self.conversation)
        log.info({"event": "session_rag_archived",
                  "archived": len(to_archive), "chunks_total": self._session_rag.chunk_count,
                  "before_chars": total_chars, "after_chars": after_chars})
        safe_print(C.gray(
            f"  [SessionRAGアーカイブ完了: {len(to_archive)}件 → RAGストア、"
            f"直近{keep_recent}件保持 ({total_chars:,}→{after_chars:,}文字)]"
        ))

    def _api_call_with_retry(self, messages: list[dict],
                             override_tool_specs: Optional[list] = None) -> dict:
        """
        Token Bucket 対応リトライループ。

        pick() が ready アカウントを返した場合 → acquire 済みなので record() 不要
        pick() が waiting アカウントを返した場合 → wait 後に record() で acquire
        429/503 受信 → 指数バックオフ後に次の pick() でローテーション

        override_tool_specs: Noneなら self.tools.get_specs() を使用。
                             []を渡すとツールなしモード（要約・検証用）。
        """
        tool_specs = override_tool_specs if override_tool_specs is not None else self.tools.get_specs()
        attempt = 0
        trim_count = 0  # 削減回数カウンタ
        # 500エラー時にペイロードを削って再リトライするための作業コピー
        working_messages = _repair_message_sequence(list(messages))

        # 推論モードをアカウント設定に一時反映
        effective_thinking = "HIGH" if self.thinking_enabled else "NONE"
        for acc in self.rotator.accounts:
            acc.thinking_level = effective_thinking

        while attempt < MAX_RETRIES:
            account, wait = self.rotator.pick()

            if wait > 0:
                jitter = random.uniform(0.05, 0.3)
                actual_wait = wait + jitter
                log.info({"event": "rpm_wait", "account": account.name,
                          "wait_sec": round(actual_wait, 2)})
                safe_print(C.yellow(f"  ⏳ RPM待機中 {actual_wait:.1f}秒 ({account.name})"), flush=True)
                time.sleep(actual_wait)
                self.rotator.record(account)

            try:
                tokens = round(account.bucket.tokens_available, 1)
                safe_print(C.gray(f"  → {account.name}  残トークン:{tokens}/{account.bucket.rpm_limit}"), flush=True)
                log.info({"event": "api_call", "account": account.name,
                          "attempt": attempt + 1,
                          "tokens": tokens,
                          "rpd_left": account.bucket.rpd_remaining,
                          "msg_count": len(working_messages)})
                response = _call_gemini_api(account, working_messages, tool_specs,
                                            system_prompt=self.system_prompt,
                                            json_mode=self.json_mode)
                log.info({"event": "api_ok", "account": account.name})
                return response

            except RateLimitError as e:
                backoff = min(BASE_BACKOFF * (2 ** attempt) + random.uniform(0, 1),
                              MAX_BACKOFF)
                log.warning({"event": "rate_limit_429", "account": account.name,
                             "backoff_sec": round(backoff, 1)})
                safe_print(C.yellow(f"  ⚠ 429 レート制限 → {backoff:.0f}秒待機してリトライ"), flush=True)
                time.sleep(backoff)
                attempt += 1

            except ServerError as e:
                backoff = min(BASE_BACKOFF * (2 ** attempt) + random.uniform(0, 2),
                              MAX_BACKOFF)
                log.warning({"event": "server_error", "account": account.name,
                             "status": e.status, "msg": e.message,
                             "backoff_sec": round(backoff, 1)})
                safe_print(C.yellow(f"  ⚠ サーバーエラー詳細: {e.message[:200]}"), flush=True)

                # 500は初回から古いメッセージを削ってペイロードを縮小して再試行
                if len(working_messages) > 4 and trim_count < 5:
                    working_messages = _trim_messages_smart(working_messages)
                    trim_count += 1
                    safe_print(C.yellow(
                        f"  ⚠ サーバーエラー({e.status}) → ペイロード削減({trim_count}/3回, 残{len(working_messages)}件) + {backoff:.0f}秒待機"
                    ), flush=True)
                    log.warning({"event": "payload_trimmed",
                                 "remaining": len(working_messages)})
                else:
                    if trim_count >= 3:
                        safe_print(C.red(f"  ✗ ペイロード削減制限(3回)に達しました"), flush=True)
                        raise RuntimeError("サーバーエラーが解消されず、ペイロード削減制限に達しました")
                    safe_print(C.yellow(f"  ⚠ サーバーエラー({e.status}) → {backoff:.0f}秒待機"), flush=True)

                time.sleep(backoff)
                attempt += 1

            except GeminiAPIError as e:
                log.error({"event": "api_error", "account": account.name,
                           "status": e.status, "msg": e.message})
                safe_print(C.red(f"  ✗ APIエラー({e.status}): {e.message}"), flush=True)
                raise

            except (http.client.RemoteDisconnected,
                    ConnectionResetError, ConnectionError, TimeoutError) as e:
                backoff = min(BASE_BACKOFF * (2 ** attempt) + random.uniform(0, 2),
                              MAX_BACKOFF)
                log.warning({"event": "connection_error", "error": str(e),
                             "backoff_sec": round(backoff, 1)})
                safe_print(C.yellow(f"  ⚠ 接続エラー → {backoff:.0f}秒待機してリトライ ({type(e).__name__})"), flush=True)
                time.sleep(backoff)
                attempt += 1

        raise RuntimeError(f"API呼び出し最大リトライ数 ({MAX_RETRIES}) を超えました")

    def _stream_react_call(
        self,
        messages: list,
        text_callback=None,
    ) -> tuple[str, list]:
        """
        ReAct 専用ストリーミング API 呼び出し。

        text_callback が None の場合はテキストを端末にリアルタイム表示する。
        text_callback が callable の場合はそちらにチャンクを渡し端末には表示しない。
        これにより呼び出し元が「中間ターンのみ表示・最終ターンは表示しない」制御ができる。

        Ctrl+C 割り込み時は ("__interrupted__", []) を返す。
        """
        tool_specs = self.tools.get_specs()
        effective_thinking = "HIGH" if self.thinking_enabled else "NONE"
        for acc in self.rotator.accounts:
            acc.thinking_level = effective_thinking

        attempt = 0
        trim_count = 0  # 削減回数カウンタ
        working_messages = _repair_message_sequence(list(messages))

        while attempt < MAX_RETRIES:
            account, wait = self.rotator.pick()

            if wait > 0:
                jitter      = random.uniform(0.05, 0.3)
                actual_wait = wait + jitter
                log.info({"event": "rpm_wait", "account": account.name,
                          "wait_sec": round(actual_wait, 2)})
                safe_print(C.yellow(f"  ⏳ RPM待機中 {actual_wait:.1f}秒 ({account.name})"),
                      flush=True)
                time.sleep(actual_wait)
                self.rotator.record(account)

            try:
                tokens = round(account.bucket.tokens_available, 1)
                safe_print(C.gray(
                    f"  → {account.name}  残トークン:{tokens}/{account.bucket.rpm_limit}"
                ), flush=True)
                log.info({"event": "api_call_stream", "account": account.name,
                          "attempt": attempt + 1, "tokens": tokens,
                          "msg_count": len(working_messages)})

                full_text:  str       = ""
                # ツール呼び出しをリストで管理（同一ツールの複数呼び出しに対応）
                tool_calls_list: list[dict] = []
                header_printed        = False  # 💭 プレフィックス表示済みフラグ

                try:
                    for text_chunk, chunk_tools, _ in _stream_gemini_api(
                        account, working_messages, tool_specs, self.system_prompt,
                        json_mode=self.json_mode
                    ):
                        if text_chunk:
                            # 💭 ヘッダーは text_callback の有無に関わらず常に表示
                            if not header_printed:
                                safe_print(f"\n  {C.purple('💭')} ", end="", flush=True)
                                header_printed = True
                            if text_callback is not None:
                                # plan モード等: 呼び出し元がチャンクを受け取って色付け
                                text_callback(text_chunk)
                            else:
                                # interactive モード: デフォルトで紫色リアルタイム表示
                                safe_print(C.purple(text_chunk), end="", flush=True)
                            full_text += text_chunk
                        for ct in chunk_tools:
                            name = ct.get("name")
                            args = ct.get("args", {})
                            # 名前があれば新規のツール呼び出しとして追加
                            if name:
                                tool_calls_list.append({"name": name, "args": dict(args)})
                            elif tool_calls_list:
                                # 名前が無い場合は最後の呼び出しの引数に追記（ストリーミング対応）
                                tool_calls_list[-1]["args"].update(args)

                except KeyboardInterrupt:
                    safe_print(C.yellow("\n\n  [割り込み] Ctrl+C — ストリームを停止しました。"),
                          flush=True)
                    return "__interrupted__", []

                if header_printed and text_callback is None:
                    safe_print()  # 直接出力モードのみ末尾改行（typewriter経由時は_twが管理）

                tool_calls = tool_calls_list
                log.info({"event": "api_ok_stream", "account": account.name,
                          "text_len": len(full_text),
                          "tool_calls": len(tool_calls)})
                return full_text, tool_calls

            except RateLimitError:
                backoff = min(BASE_BACKOFF * (2 ** attempt) + random.uniform(0, 1),
                              MAX_BACKOFF)
                log.warning({"event": "rate_limit_429", "account": account.name,
                             "backoff_sec": round(backoff, 1)})
                safe_print(C.yellow(f"  ⚠ 429 レート制限 → {backoff:.0f}秒待機してリトライ"),
                      flush=True)
                time.sleep(backoff)
                attempt += 1

            except ServerError as e:
                backoff = min(BASE_BACKOFF * (2 ** attempt) + random.uniform(0, 2),
                              MAX_BACKOFF)
                # 初回エラー時のみ送信内容の構造をダンプ
                if attempt == 0:
                    contents_debug = _to_gemini_contents(working_messages)
                    struct = [
                        {"role": c["role"],
                         "part_types": [list(p.keys())[0] for p in c.get("parts", [])]}
                        for c in contents_debug
                    ]
                    tool_names = [s.get("name") for s in tool_specs[:5]] if tool_specs else []
                    log.warning({"event": "server_error_payload_dump",
                                 "model": account.model,
                                 "contents_structure": struct,
                                 "msg_count": len(working_messages),
                                 "tool_specs_count": len(tool_specs),
                                 "tool_names_sample": tool_names})
                    safe_print(C.yellow(
                        f"  ⚠ 送信内容構造: {struct}\n"
                        f"  ⚠ モデル: {account.model}  tool_specs数: {len(tool_specs)}"
                        f"  ツール例: {tool_names}"
                    ), flush=True)
                log.warning({"event": "server_error_stream", "account": account.name,
                             "status": e.status, "msg": e.message,
                             "backoff_sec": round(backoff, 1)})
                safe_print(C.yellow(f"  ⚠ サーバーエラー詳細: {e.message[:200]}"), flush=True)

                # 500は初回から古いメッセージを削ってペイロードを縮小して再試行
                if len(working_messages) > 4 and trim_count < 5:
                    working_messages = _trim_messages_smart(working_messages)
                    trim_count += 1
                    safe_print(C.yellow(
                        f"  ⚠ サーバーエラー({e.status}) → ペイロード削減({trim_count}/3回, 残{len(working_messages)}件) + {backoff:.0f}秒待機"
                    ), flush=True)
                    log.warning({"event": "payload_trimmed_stream",
                                 "remaining": len(working_messages)})
                else:
                    if trim_count >= 3:
                        safe_print(C.red(f"  ✗ ペイロード削減制限(3回)に達しました"), flush=True)
                        raise RuntimeError("サーバーエラーが解消されず、ペイロード削減制限に達しました")
                    safe_print(C.yellow(f"  ⚠ サーバーエラー({e.status}) → {backoff:.0f}秒待機"), flush=True)

                time.sleep(backoff)
                attempt += 1

            except GeminiAPIError as e:
                log.error({"event": "api_error", "account": account.name,
                           "status": e.status, "msg": e.message})
                safe_print(C.red(f"  ✗ APIエラー({e.status}): {e.message}"), flush=True)
                raise

            except (http.client.RemoteDisconnected,
                    ConnectionResetError, ConnectionError, TimeoutError) as e:
                backoff = min(BASE_BACKOFF * (2 ** attempt) + random.uniform(0, 2),
                              MAX_BACKOFF)
                log.warning({"event": "connection_error", "error": str(e),
                             "backoff_sec": round(backoff, 1)})
                safe_print(C.yellow(
                    f"  ⚠ 接続エラー → {backoff:.0f}秒待機してリトライ ({type(e).__name__})"
                ), flush=True)
                time.sleep(backoff)
                attempt += 1

        raise RuntimeError(
            f"ストリーミング API 最大リトライ数 ({MAX_RETRIES}) を超えました"
        )

    def _extract_text(self, response: dict) -> Optional[str]:
        try:
            parts = response["candidates"][0]["content"]["parts"]
            texts = [p["text"] for p in parts if "text" in p]
            return "\n".join(texts) if texts else None
        except (KeyError, IndexError):
            return None

    def _extract_tool_calls(self, response: dict) -> list[dict]:
        try:
            parts = response["candidates"][0]["content"]["parts"]
            return [p["functionCall"] for p in parts if "functionCall" in p]
        except (KeyError, IndexError):
            return []

    def _finish_reason(self, response: dict) -> str:
        try:
            return response["candidates"][0].get("finishReason", "UNKNOWN")
        except (KeyError, IndexError):
            return "UNKNOWN"

    def _make_cache_key(self, fn_name: str, fn_args: dict) -> str:
        return f"{fn_name}:{json.dumps(fn_args, sort_keys=True, ensure_ascii=False)}"

    def _invalidate_cache_for_path(self, path: str):
        """ファイル書き込み後に該当パスの read_file・list_directory キャッシュを削除する。"""
        path_json  = json.dumps(path, ensure_ascii=False)
        parent_dir = str(Path(path).parent)
        dir_key    = self._make_cache_key("list_directory", {"path": parent_dir})
        with self._tool_cache_lock:
            for key in list(self._tool_cache):
                if key.startswith("read_file:") and path_json in key:
                    self._tool_cache.pop(key, None)
                elif key == dir_key:
                    self._tool_cache.pop(key, None)
        if self._project_rag is not None and path:
            try:
                api_key = self.rotator.pick()[0].api_key
                self._project_rag.update_file(path, api_key)
            except Exception as _e:
                log.warning({"event": "project_rag_update_error", "path": path, "error": str(_e)})

    def _run_single_tool(self, tc: dict) -> tuple[str, str]:
        """
        1ツール呼び出しを実行して (fn_name, result_str) を返す。
        並列実行から呼ばれるためスレッドセーフ。
        キャッシュ対象ツールはセッション内で結果を再利用する。
        """
        fn_name = tc.get("name", "")
        fn_args = tc.get("args", {})
        args_preview = ", ".join(f"{k}={repr(v)[:40]}" for k, v in fn_args.items())
        safe_print(C.bold_green(f"  ⚙ ") + C.green(fn_name) + C.cyan(f"({args_preview})"), flush=True)

        # ── キャッシュヒット確認（読み取り系のみ）────────────────
        if fn_name in _CACHEABLE_TOOLS:
            cache_key = self._make_cache_key(fn_name, fn_args)
            with self._tool_cache_lock:
                cached = self._tool_cache.get(cache_key)
            if cached is not None:
                safe_print(C.gray(f"    [キャッシュ] {len(cached)}文字 (再取得スキップ)"), flush=True)
                return fn_name, cached

        # ── Plan モードのdiff表示（write_file / edit_file）────────
        _print_write_diff(fn_name, fn_args)

        # ── run_powershell のカレントディレクトリ強制同期 ───────
        if fn_name == "run_powershell":
            if not fn_args.get("working_directory"):
                fn_args["working_directory"] = self.cwd

        try:
            result = self.tools.execute(fn_name, fn_args)
            result_str = cache_tool_output(fn_name, str(result))
        except Exception as e:
            result_str = f"ツール実行エラー: {fn_name}: {e}"
            log.error({"event": "tool_error", "tool": fn_name, "error": str(e)})
            safe_print(C.red(f"    ✗ {e}"), flush=True)
            return fn_name, result_str

        # ── キャッシュ登録 / 書き込み後キャッシュ無効化 ──────────
        if fn_name in _CACHEABLE_TOOLS:
            with self._tool_cache_lock:
                self._tool_cache[cache_key] = result_str  # type: ignore[possibly-undefined]
        elif fn_name in ("write_file", "edit_file", "patch_file", "delete_file"):
            self._invalidate_cache_for_path(fn_args.get("path", ""))

        log.info({"event": "tool_result", "tool": fn_name, "result_len": len(result_str)})
        safe_print(C.cyan(f"    → {len(result_str)}文字 取得"), flush=True)
        return fn_name, result_str

    def run(self, user_message: str) -> str:
        """
        エージェントループのエントリポイント。
        user_message に対して最終応答を文字列で返す。
        """
        # 必要に応じて会話を圧縮
        self._compact_if_needed()
        clear_read_files_registry()

        # コンテキストヘッダー（作業フォルダ・タスクゴール）をユーザーメッセージの先頭に付加
        context_header = self._build_context_header()
        task_ctx = self._task_context()
        prefix_parts = [p for p in [context_header, task_ctx] if p]
        if prefix_parts:
            augmented_message = "\n\n".join(prefix_parts) + "\n\n" + user_message
        else:
            augmented_message = user_message

        # SessionRAG から関連チャンクを検索してコンテキストに注入
        if self._session_rag and self._session_rag.chunk_count > 0:
            try:
                api_key = self.rotator.pick()[0].api_key
                retrieved = self._session_rag.retrieve(user_message, api_key)
                if retrieved:
                    rag_ctx = self._session_rag.format_context(retrieved)
                    augmented_message = rag_ctx + "\n\n" + augmented_message
                    safe_print(C.gray(
                        f"  [SessionRAG] {len(retrieved)}件の関連情報を注入 "
                        f"(ストア: {self._session_rag.chunk_count}チャンク)"
                    ), flush=True)
            except Exception as _e:
                log.warning({"event": "session_rag_retrieve_error", "error": str(_e)})

        # ProjectRAG: 共有インスタンスを使用。未インデックスの場合のみ非同期でインデックス開始
        if self._project_rag:
            try:
                rag_key = self.rotator.pick()[0].api_key

                if self._project_rag.chunk_count > 0:
                    p_retrieved = self._project_rag.retrieve(user_message, rag_key)
                    if p_retrieved:
                        p_ctx = self._project_rag.format_context(p_retrieved)
                        augmented_message = p_ctx + "\n\n" + augmented_message
                        safe_print(C.gray(
                            f"  [ProjectRAG] {len(p_retrieved)}件のコード参照を注入 "
                            f"(ストア: {self._project_rag.chunk_count}チャンク)"
                        ), flush=True)
                else:
                    # 未インデックス時のみバックグラウンドでインデックス開始
                    def _bg_index():
                        try:
                            idx_acc, _ = self.rotator.pick()
                            n = self._project_rag.index_directory(self.cwd, idx_acc.api_key)
                            if n > 0:
                                safe_print(C.gray(f"  [ProjectRAG] 新規インデックス完了: {n}チャンク"), flush=True)
                                self._project_rag.save(self.cwd)
                        except Exception as _ie:
                            log.warning({"event": "project_rag_index_error", "error": str(_ie)})
                    threading.Thread(target=_bg_index, daemon=True).start()

            except Exception as _e:
                log.warning({"event": "project_rag_retrieve_error", "error": str(_e)})

        # 会話履歴を構築（system_prompt は _call_gemini_api で systemInstruction として送信）
        messages: list[dict] = []
        messages.extend(self.conversation)
        old_conv_len = len(self.conversation)  # ツール実行履歴保存用にターン開始時の長さを記録
        messages.append({"role": "user", "content": augmented_message})

        tool_round = 0

        while tool_round < MAX_TOOL_ROUNDS:
            response = self._api_call_with_retry(messages)
            finish = self._finish_reason(response)
            text = self._extract_text(response)
            tool_calls = self._extract_tool_calls(response)

            log.info({"event": "response", "finish_reason": finish,
                      "has_text": text is not None,
                      "tool_calls": len(tool_calls)})

            # ── ツール呼び出しがある場合 ──
            if tool_calls and finish in ("STOP", "TOOL_CALLS", "OTHER", ""):
                tool_round += 1
                if tool_round > MAX_TOOL_ROUNDS:
                    log.warning({"event": "tool_limit_reached"})
                    break

                # アシスタントの応答をメッセージ履歴に追加（functionCall 正式形式）
                messages.append({
                    "role": "assistant",
                    "content": text or "",
                    "function_calls": [
                        {"name": tc["name"], "args": tc.get("args", {})}
                        for tc in tool_calls
                    ],
                })

                # ── ツール実行（複数なら並列）─────────────────────────
                if len(tool_calls) > 1:
                    safe_print(C.orange(f"  ⚡ {len(tool_calls)} ツールを並列実行"), flush=True)
                    ordered: list[Optional[dict]] = [None] * len(tool_calls)
                    with ThreadPoolExecutor(max_workers=len(tool_calls)) as tpool:
                        fmap = {
                            tpool.submit(self._run_single_tool, tc): i
                            for i, tc in enumerate(tool_calls)
                        }
                        for f in as_completed(fmap):
                            idx = fmap[f]
                            try:
                                fn_name, result_str = f.result()
                            except Exception as e:
                                tc = tool_calls[idx]
                                fn_name = tc.get("name", "unknown")
                                result_str = f"ツール実行エラー: {e}"
                                log.error({"event": "parallel_tool_error",
                                           "tool": fn_name, "error": str(e)})
                            ordered[idx] = {
                                "tool": fn_name,
                                "result": result_str,
                            }
                    tool_results = [r for r in ordered if r is not None]
                else:
                    fn_name, result_str = self._run_single_tool(tool_calls[0])
                    tool_results = [{"tool": fn_name,
                                     "result": result_str}]

                # ツール結果を functionResponse 正式形式でメッセージに追加
                messages.append({
                    "role": "user",
                    "content": "",
                    "function_results": [
                        {"name": r["tool"], "result": r["result"]}
                        for r in tool_results
                    ],
                })
                continue

            # ── 最終応答 ──
            final_text = text or "(応答なし)"

            # 会話履歴を更新（ツール実行履歴を含む全ターンを保存）
            # old_conv_len+1 以降 = ツール交換メッセージ（augmented_userの次から）
            self.conversation.append({"role": "user", "content": user_message})
            self.conversation.extend(messages[old_conv_len + 1:])
            self.conversation.append({"role": "assistant", "content": final_text})

            return final_text

        return "エラー: ツール呼び出しの上限に達しました"

    def run_stream(self, user_message: str, callback=None) -> str:
        """
        エージェントループのストリーミング版。
        callback(text_chunk: str) にトークンを逐次送信しながら最終応答を返す。
        callback=None の場合は端末にリアルタイム表示する。
        """
        self._compact_if_needed()
        clear_read_files_registry()

        context_header = self._build_context_header()
        task_ctx = self._task_context()
        prefix_parts = [p for p in [context_header, task_ctx] if p]
        augmented_message = (
            "\n\n".join(prefix_parts) + "\n\n" + user_message if prefix_parts else user_message
        )

        # SessionRAG から関連チャンクを検索してコンテキストに注入
        if self._session_rag and self._session_rag.chunk_count > 0:
            try:
                api_key = self.rotator.pick()[0].api_key
                retrieved = self._session_rag.retrieve(user_message, api_key)
                if retrieved:
                    rag_ctx = self._session_rag.format_context(retrieved)
                    augmented_message = rag_ctx + "\n\n" + augmented_message
                    safe_print(C.gray(
                        f"  [SessionRAG] {len(retrieved)}件の関連情報を注入 "
                        f"(ストア: {self._session_rag.chunk_count}チャンク)"
                    ), flush=True)
            except Exception as _e:
                log.warning({"event": "session_rag_retrieve_error", "error": str(_e)})

        # ProjectRAG: 初回呼び出し時にコードベースを非同期インデックス、以降は検索結果を注入
        try:
            api_key = self.rotator.pick()[0].api_key
            if self._project_rag is None:
                self._project_rag = ProjectRAG()
                def _bg_index_stream():
                    try:
                        n = self._project_rag.index_directory(self.cwd, api_key)
                        safe_print(C.gray(f"  [ProjectRAG] インデックス完了: {n}チャンク"), flush=True)
                    except Exception as _ie:
                        log.warning({"event": "project_rag_index_error", "error": str(_ie)})
                threading.Thread(target=_bg_index_stream, daemon=True).start()
            elif self._project_rag.chunk_count > 0:
                p_retrieved = self._project_rag.retrieve(user_message, api_key)
                if p_retrieved:
                    p_ctx = self._project_rag.format_context(p_retrieved)
                    augmented_message = p_ctx + "\n\n" + augmented_message
                    safe_print(C.gray(
                        f"  [ProjectRAG] {len(p_retrieved)}件のコード参照を注入 "
                        f"(ストア: {self._project_rag.chunk_count}チャンク)"
                    ), flush=True)
        except Exception as _e:
            log.warning({"event": "project_rag_retrieve_error", "error": str(_e)})

        messages: list[dict] = []
        messages.extend(self.conversation)
        old_conv_len = len(self.conversation)
        messages.append({"role": "user", "content": augmented_message})

        tool_round = 0

        while tool_round < MAX_TOOL_ROUNDS:
            text, tool_calls = self._stream_react_call(messages, text_callback=callback)

            if text == "__interrupted__":
                return "ユーザーによって中断されました"

            log.info({"event": "response_stream", "has_text": bool(text),
                      "tool_calls": len(tool_calls)})

            if tool_calls:
                tool_round += 1
                if tool_round > MAX_TOOL_ROUNDS:
                    log.warning({"event": "tool_limit_reached"})
                    break

                messages.append({
                    "role": "assistant",
                    "content": text or "",
                    "function_calls": [
                        {"name": tc["name"], "args": tc.get("args", {})}
                        for tc in tool_calls
                    ],
                })

                if len(tool_calls) > 1:
                    safe_print(C.orange(f"  ⚡ {len(tool_calls)} ツールを並列実行"), flush=True)
                    ordered: list[Optional[dict]] = [None] * len(tool_calls)
                    with ThreadPoolExecutor(max_workers=len(tool_calls)) as tpool:
                        fmap = {
                            tpool.submit(self._run_single_tool, tc): i
                            for i, tc in enumerate(tool_calls)
                        }
                        for f in as_completed(fmap):
                            idx = fmap[f]
                            try:
                                fn_name, result_str = f.result()
                            except Exception as e:
                                tc = tool_calls[idx]
                                fn_name = tc.get("name", "unknown")
                                result_str = f"ツール実行エラー: {e}"
                                log.error({"event": "parallel_tool_error",
                                           "tool": fn_name, "error": str(e)})
                            ordered[idx] = {
                                "tool": fn_name,
                                "result": result_str,
                            }
                    tool_results = [r for r in ordered if r is not None]
                else:
                    fn_name, result_str = self._run_single_tool(tool_calls[0])
                    tool_results = [{"tool": fn_name,
                                     "result": result_str}]

                messages.append({
                    "role": "user",
                    "content": "",
                    "function_results": [
                        {"name": r["tool"], "result": r["result"]}
                        for r in tool_results
                    ],
                })
                continue

            final_text = text or "(応答なし)"
            self.conversation.append({"role": "user", "content": user_message})
            self.conversation.extend(messages[old_conv_len + 1:])
            self.conversation.append({"role": "assistant", "content": final_text})
            return final_text

        return "エラー: ツール呼び出しの上限に達しました"

    def clear_history(self):
        self.conversation = []
        self._tool_cache.clear()
        self.end_task()

    def print_status(self):
        status = self.rotator.status()
        safe_print("\n=== アカウントステータス (Token Bucket) ===")
        for s in status:
            tokens = s["tokens_available"]
            rpm_limit = s["rpm_limit"]
            filled = int(tokens)
            bar = "█" * filled + "░" * (rpm_limit - filled)
            rpd_str = "無制限 ∞" if s["rpd_unlimited"] else f"{s['rpd_remaining']} remaining"
            safe_print(f"  [{s['name']}] {s['model']}")
            safe_print(f"    RPM Bucket: [{bar}] {tokens:.1f}/{rpm_limit} tokens")
            safe_print(f"    RPD:        {rpd_str}")
        safe_print()

