# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import json
import os
import sys
import time
import re
import threading
from pathlib import Path
from typing import Optional
from v4_modules.utils import safe_print, C, log
from v4_modules.tools import ExecutionRegistry
from v4_modules.agent import GeminiAgent


cmd_registry = ExecutionRegistry()

MODEL_LIST = [
    ("1", "gemma-4-31b-it",     "Gemma 4 31B Dense   — 最高精度・推論最強"),
    ("2", "gemma-4-26b-a4b-it", "Gemma 4 26B MoE     — 高速・精度も高い"),
]

@cmd_registry.register("status", "レート制限状態を表示")
def cmd_status(agent: GeminiAgent, args: str):
    agent.print_status()

@cmd_registry.register("clear", "会話履歴をリセット")
def cmd_clear(agent: GeminiAgent, args: str):
    agent.clear_history()
    safe_print("会話履歴をクリアしました。")

# Gemma 4 向け推論指示（system_prompt への注入・除去で切り替える）
_THINKING_INSTRUCTION = (
    "行動・回答する前に必ず<thinking>タグ内で問題を段階的に深く推論・分析し、"
    "複数の選択肢を検討してから最善策を実行してください。"
)

@cmd_registry.register("think", "推論モードの確認・切替 (/think on|off)")
def cmd_think(agent: GeminiAgent, args: str):
    arg = args.strip().lower()
    if arg == "on":
        agent.set_thinking(True)
        # system_prompt に推論指示がなければ末尾に追加
        if agent.system_prompt and _THINKING_INSTRUCTION not in agent.system_prompt:
            agent.system_prompt = agent.system_prompt.rstrip() + "\n" + _THINKING_INSTRUCTION
        safe_print(C.green("  推論モード: ON  — <thinking> 指示をプロンプトに注入しました。"))
    elif arg == "off":
        agent.set_thinking(False)
        # system_prompt から推論指示を除去
        if agent.system_prompt:
            agent.system_prompt = agent.system_prompt.replace(
                "\n" + _THINKING_INSTRUCTION, ""
            ).replace(_THINKING_INSTRUCTION, "")
        safe_print(C.yellow("  推論モード: OFF — <thinking> 指示をプロンプトから除去しました。"))
    else:
        state = "ON" if agent.thinking_enabled else "OFF"
        injected = agent.system_prompt and _THINKING_INSTRUCTION in (agent.system_prompt or "")
        prompt_mark = C.green("注入済み") if injected else C.gray("未注入")
        safe_print(f"  推論モード: {C.green('ON') if agent.thinking_enabled else C.yellow('OFF')}"
                   f"  (プロンプト指示: {prompt_mark})")
        safe_print(C.gray("  切替: /think on  または  /think off"))

@cmd_registry.register("model", "モデルの確認・切替 (/model 1|2|<名前>)")
def cmd_model(agent: GeminiAgent, args: str):
    if not args:
        current = agent.rotator.accounts[0].model
        safe_print("  利用可能なモデル:")
        for num, name, desc in MODEL_LIST:
            marker = " <<" if name == current else ""
            safe_print(f"    {num}: {desc}{marker}")
        safe_print("  切替例: /model 1")
        return
    matched = None
    for num, name, desc in MODEL_LIST:
        if args == num or args == name:
            matched = (name, desc)
            break
    if matched:
        new_model, desc = matched
        for acc in agent.rotator.accounts:
            acc.model = new_model
        agent.clear_history()
        safe_print(f"  モデル変更: {desc}")
        safe_print("  会話履歴をリセットしました。")
    else:
        for acc in agent.rotator.accounts:
            acc.model = args
        agent.clear_history()
        safe_print(f"  モデルを変更しました: {args}")
        safe_print("  会話履歴をリセットしました。")

@cmd_registry.register("cd", "作業フォルダの確認・変更 (/cd <パス>)")
def cmd_cd(agent: GeminiAgent, args: str):
    if not args:
        safe_print(f"  現在の作業フォルダ: {agent.cwd}")
        return
    new_path = args.strip().strip('"').strip("'")
    expanded = str(Path(new_path).expanduser().resolve())
    if Path(expanded).exists():
        agent.set_cwd(expanded)
    else:
        safe_print(f"  フォルダが見つかりません: {expanded}")

@cmd_registry.register("task", "タスクの確認・開始 (/task <ゴール> | end)")
def cmd_task(agent: GeminiAgent, args: str):
    if args.lower() == "end":
        agent.end_task()
        safe_print("  タスクを終了しました。")
    elif args:
        agent.start_task(args)
        safe_print(f"  タスク開始: {args}")
    else:
        if agent._task_goal:
            safe_print(f"  現在のタスク: {agent._task_goal}")
        else:
            safe_print("  タスクなし（/task <ゴール> で開始）")

@cmd_registry.register("help", "コマンド一覧を表示")
def cmd_help(agent: GeminiAgent, args: str):
    safe_print(cmd_registry.help_text())

