# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Any
from v4_modules.utils import safe_print, C, log, TokenBucket


@dataclass
class AccountConfig:
    """1 Gemini アカウントの設定"""
    name: str
    api_key: str
    model: str = field(default_factory=lambda: _DEFAULT_MODEL)
    rpm_limit: int = 15
    rpd_limit: int = 1500
    thinking_level: str = "HIGH"   # HIGH / MEDIUM / LOW / NONE
    bucket: TokenBucket = field(init=False)

    def __post_init__(self):
        self.bucket = TokenBucket(
            rpm_limit=self.rpm_limit,
            rpd_limit=self.rpd_limit,
        )

@dataclass(frozen=True)
class PortContext:
    """作業フォルダの構造スナップショット（不変）"""
    cwd: Path
    py_file_count: int       # 再帰的な .py ファイル数
    has_tests: bool          # tests/ フォルダまたは test_*.py の存在
    has_config: bool         # .json / .env 系設定ファイルの存在
    top_files: tuple         # フォルダ直下の上位10件
    py_files: tuple          # 直下の .py ファイル（上位5件）
    cfg_files: tuple         # 直下の設定ファイル（上位5件）

def build_port_context(cwd: Path) -> PortContext:
    """作業フォルダを走査して PortContext を構築する"""
    try:
        top_files = tuple(
            e.name + ("/" if e.is_dir() else "")
            for e in sorted(cwd.iterdir(), key=lambda x: (x.is_file(), x.name))[:10]
        )
    except Exception as _e:
        log.warning({"event": "build_port_context_error", "phase": "iterdir", "error": str(_e)})
        top_files = ()

    try:
        py_files = tuple(f.name for f in cwd.glob("*.py"))[:5]
        cfg_files = tuple(
            f.name for f in list(cwd.glob("*.json")) + list(cwd.glob("*.env*"))
        )[:5]
        py_file_count = sum(1 for p in cwd.rglob("*.py") if p.is_file())
        has_tests = (cwd / "tests").is_dir() or any(
            f.name.startswith("test_") for f in cwd.glob("*.py")
        )
    except Exception as _e:
        log.warning({"event": "build_port_context_error", "phase": "glob", "error": str(_e)})
        py_files = cfg_files = ()
        py_file_count = 0
        has_tests = False

    return PortContext(
        cwd=cwd,
        py_file_count=py_file_count,
        has_tests=has_tests,
        has_config=bool(cfg_files),
        top_files=top_files,
        py_files=py_files,
        cfg_files=cfg_files,
    )

def render_port_context(ctx: PortContext) -> str:
    """PortContext をシステムプロンプト注入用テキストに変換する"""
    lines = ["[実行コンテキスト]", f"作業フォルダ: {ctx.cwd}"]
    if ctx.py_file_count:
        lines.append(f"Pythonファイル数: {ctx.py_file_count}（再帰）")
    if ctx.top_files:
        lines.append(f"フォルダ内容: {', '.join(ctx.top_files)}")
    if ctx.py_files:
        lines.append(f"Pythonファイル: {', '.join(ctx.py_files)}")
    if ctx.cfg_files:
        lines.append(f"設定ファイル: {', '.join(ctx.cfg_files)}")
    if ctx.has_tests:
        lines.append("テスト: あり（tests/ または test_*.py）")
    return "\n".join(lines)

GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models"

_DEFAULT_MODEL      = "gemini-2.0-flash"

_EMBEDDING_MODEL    = "gemini-embedding-2-preview"

_HYDE_MODEL         = "gemini-2.0-flash-lite"

_DEFAULT_CWD: Optional[str] = None

def _parse_env_file(env_path: Path) -> dict[str, str]:
    """
    .env ファイルをパースして {KEY: VALUE} の辞書を返す。
    標準ライブラリのみ使用（python-dotenv 不要）。
    対応形式:
      KEY=VALUE
      KEY="VALUE"
      KEY='VALUE'
      # コメント行は無視
    """
    result: dict[str, str] = {}
    for line in env_path.read_text(encoding="utf-8-sig", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip()
        # クォート除去
        if (val.startswith('"') and val.endswith('"')) or \
           (val.startswith("'") and val.endswith("'")):
            val = val[1:-1]
        result[key] = val
    return result

def _generate_env_template(env_path: Path):
    template = """\
# ==============================================
# unimog / Gemini Agent 設定ファイル
# ==============================================
# Gemini APIキー（Google AI Studio で取得）
# https://aistudio.google.com/app/apikey

GEMINI_KEY_1=YOUR_API_KEY_1
GEMINI_KEY_2=YOUR_API_KEY_2
GEMINI_KEY_3=YOUR_API_KEY_3

# 使用するモデル名（3アカウント共通）
GEMINI_MODEL=gemini-2.0-flash

# Embedding・HyDE用モデル（省略時はデフォルト値を使用）
# EMBEDDING_MODEL=gemini-embedding-2-preview
# HYDE_MODEL=gemini-2.0-flash-lite

# レート制限（無料枠: RPM=15, RPD=1500）
GEMINI_RPM=15
GEMINI_RPD=1500

# システムプロンプト
SYSTEM_PROMPT=あなたは有能なAIアシスタントです。日本語で丁寧に回答してください。
"""
    env_path.write_text(template, encoding="utf-8")

def load_config(base_dir: Optional[str] = None) -> tuple[list[AccountConfig], str]:
    """
    設定を読み込む。
      .env が存在する場合 → GEMINI_KEY_x からアカウントを構築
      存在しない         → テンプレートを生成して終了
    """
    search_dir = Path(base_dir) if base_dir else Path(__file__).parent
    env_path   = search_dir / ".env"

    # ── .env が存在する場合 ──────────────────────────────────────
    if env_path.exists():
        env = _parse_env_file(env_path)

        # モデル名グローバルを .env の値で上書き
        global _DEFAULT_MODEL, _EMBEDDING_MODEL, _HYDE_MODEL, _DEFAULT_CWD
        _DEFAULT_MODEL   = env.get("GEMINI_MODEL",   _DEFAULT_MODEL)
        _EMBEDDING_MODEL = env.get("EMBEDDING_MODEL", _EMBEDDING_MODEL)
        _HYDE_MODEL      = env.get("HYDE_MODEL",      _HYDE_MODEL)
        _DEFAULT_CWD     = os.environ.get("UNIMOG_CWD") or env.get("DEFAULT_CWD", None)

        model      = _DEFAULT_MODEL  # アカウントごとの上書きベース
        rpm_limit  = int(env.get("GEMINI_RPM", "15"))
        # GEMINI_RPD=0 または GEMINI_RPD=unlimited で RPD無制限モード
        rpd_raw    = env.get("GEMINI_RPD", "1500").strip().lower()
        rpd_limit  = 0 if rpd_raw in ("0", "unlimited", "none", "") else int(rpd_raw)
        system_prompt = env.get("SYSTEM_PROMPT", "")
        # GEMINI_THINKING: HIGH / MEDIUM / LOW / NONE（デフォルト HIGH）
        thinking_level = env.get("GEMINI_THINKING", "HIGH").strip().upper()

        accounts = []
        for i in range(1, 10):  # KEY_1 〜 KEY_9 まで対応
            key = env.get(f"GEMINI_KEY_{i}", "")
            if not key or key.startswith("YOUR_"):
                continue
            # アカウントごとにモデル上書き可能（例: GEMINI_MODEL_2=gemma-4-26b-a4b-it）
            acc_model = env.get(f"GEMINI_MODEL_{i}", model)
            acc_rpm   = int(env.get(f"GEMINI_RPM_{i}", str(rpm_limit)))
            acc_rpd_raw = env.get(f"GEMINI_RPD_{i}", rpd_raw)
            acc_rpd   = 0 if acc_rpd_raw.strip().lower() in ("0","unlimited","none","") else int(acc_rpd_raw)
            accounts.append(AccountConfig(
                name=f"account_{i}",
                api_key=key,
                model=acc_model,
                rpm_limit=acc_rpm,
                rpd_limit=acc_rpd,
                thinking_level=thinking_level,
            ))

        if not accounts:
            safe_print("[エラー] .env ファイルに有効な GEMINI_KEY_x が見つかりません。")
            safe_print(f"  {env_path} を開いてAPIキーを設定してください。")
            sys.exit(1)

        log.info({"event": "config_loaded", "source": ".env", "accounts": len(accounts)})
        return accounts, system_prompt

    # ── .env が存在しない → テンプレートを生成 ──────────────────
    _generate_env_template(env_path)
    safe_print("=" * 55)
    safe_print("  設定ファイルを生成しました。")
    safe_print("=" * 55)
    safe_print(f"\n  推奨: .env ファイルにAPIキーを設定してください")
    safe_print(f"  場所: {env_path}")
    safe_print()
    safe_print("  設定例:")
    safe_print("    GEMINI_KEY_1=AIzaSyXXXXXXXXXXXXXXXXXXX")
    safe_print("    GEMINI_KEY_2=AIzaSyYYYYYYYYYYYYYYYYYYY")
    safe_print("    GEMINI_KEY_3=AIzaSyZZZZZZZZZZZZZZZZZZZ")
    safe_print()
    safe_print("  設定後、もう一度 unimog2 を実行してください。")
    safe_print("=" * 55)
    sys.exit(0)

