# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import sys
import os
import json
import time
import threading
import io
import traceback
from pathlib import Path
from typing import Optional
from dataclasses import dataclass, field
from v4_modules.utils import safe_print, C, log, print_ascii_art, render_markdown
from v4_modules.config import load_config, AccountConfig
from v4_modules.agent import GeminiAgent
from v4_modules.tools import ToolRegistry, tools, set_write_approval_handler
from v4_modules.rag import LongTermMemory
from v4_modules.autogit import AutoGit
from v4_modules.orchestrator import InteractiveOrchestrator, AgentOrchestrator
from v4_modules.commands import cmd_registry


def interactive_loop(
    agent: "GeminiAgent",
    orchestrator: "AgentOrchestrator",
    interactive_orch: "InteractiveOrchestrator",
    auto_git: "AutoGit",
    react_prompt: str,
    plan_prompt: str,
):
    """
    ハイブリッドエージェントのメインループ。

    interactive (ReAct) モードと plan (Plan-and-Execute) モードを
    /mode コマンドでシームレスに切り替えられる。
    デフォルトは interactive モード。
    """
    def _react_approval_handler(tool_name: str, args: dict, preview: str) -> bool:
        from v4_modules.utils import safe_print, C
        path = args.get("path", "?")
        safe_print(C.yellow(f"\n  ┌─ 書き込み確認 ──────────────────────────────────────"))
        safe_print(C.yellow(f"  │  ツール : {tool_name}"))
        safe_print(C.yellow(f"  │  ファイル: {path}"))
        safe_print(C.yellow(f"  │"))
        for line in preview.splitlines():
            safe_print(C.gray(f"  │  {line}"))
        safe_print(C.yellow(f"  └──────────────────────────────────────────────────────"))
        safe_print(C.bold_green("  実行しますか？ [y/N]: "), end="", flush=True)
        try:
            response = sys.stdin.readline().strip().lower()
        except (EOFError, KeyboardInterrupt):
            response = "n"
        approved = response == "y"
        if approved:
            safe_print(C.green("  ✓ 承認しました"))
        else:
            safe_print(C.red("  ✗ 拒否しました（スキップします）"))
        return approved

    set_write_approval_handler(_react_approval_handler)
    current_mode = "interactive"

    def _mode_label(mode: str) -> str:
        return (
            C.bold_green("Interactive (ReAct)")
            if mode == "interactive"
            else C.green("Plan-and-Execute")
        )

    def switch_mode(new_mode: str):
        nonlocal current_mode
        if new_mode == current_mode:
            safe_print(C.gray(f"  既に {_mode_label(new_mode)} モードです。"))
            return
        current_mode = new_mode
        agent.set_system_prompt(react_prompt if new_mode == "interactive" else plan_prompt)
        agent.clear_history()
        interactive_orch.react_log.clear()
        safe_print(C.yellow(f"  モード切り替え: {_mode_label(new_mode)}"))
        safe_print(C.gray("  会話履歴をリセットしました。"))

    # ── モード・ユーティリティコマンドをここで登録 ──────────────
    @cmd_registry.register("mode", "モード切り替え (/mode interactive|plan)")
    def cmd_mode(a: "GeminiAgent", args: str):
        m = args.strip().lower()
        if m in ("interactive", "react", "i"):
            switch_mode("interactive")
        elif m in ("plan", "p"):
            switch_mode("plan")
        else:
            safe_print(f"  現在: {_mode_label(current_mode)}")
            safe_print(C.gray("  切替: /mode interactive  または  /mode plan"))

    @cmd_registry.register("undo", "Auto-Git でロールバック (/undo)")
    def cmd_undo(a: "GeminiAgent", args: str):
        result = auto_git.rollback(a.cwd)
        safe_print(C.yellow(f"  [AutoGit] {result}"))

    @cmd_registry.register("diff", "バックアップからの差分を表示 (/diff)")
    def cmd_diff(a: "GeminiAgent", args: str):
        out = auto_git.diff(a.cwd)
        safe_print(C.gray("  [AutoGit diff]"))
        safe_print(out)

    @cmd_registry.register("history", "ReActログを表示 (/history)")
    def cmd_history(a: "GeminiAgent", args: str):
        interactive_orch.react_log.display()

    @cmd_registry.register("export", "ReActログを Markdown で書き出す (/export [path])")
    def cmd_export(a: "GeminiAgent", args: str):
        path = args.strip() or str(Path(a.cwd) / "react_log.md")
        result = interactive_orch.react_log.export_markdown(path)
        safe_print(C.green(f"  {result}"))

    @cmd_registry.register(
        "autoexport",
        "ReActログの定期自動エクスポート (/autoexport <分> [path] | off | status)"
    )
    def cmd_autoexport(a: "GeminiAgent", args: str):
        rl  = interactive_orch.react_log
        arg = args.strip()

        # ── off: 停止 ─────────────────────────────────────────────
        if arg.lower() in ("off", "stop", "0"):
            rl.stop_auto_export()
            rl._auto_export_path     = None
            rl._auto_export_interval = 0
            safe_print(C.yellow("  [AutoExport] 停止しました。"))
            return

        # ── status: 現在の設定を表示 ──────────────────────────────
        if arg.lower() in ("status", ""):
            if rl.auto_export_enabled:
                mins = rl._auto_export_interval // 60
                secs = rl._auto_export_interval % 60
                interval_str = (f"{mins}分{secs}秒" if secs else f"{mins}分")
                safe_print(C.green(
                    f"  [AutoExport] ON  —  {interval_str}ごと  →  {rl._auto_export_path}"
                ))
            else:
                safe_print(C.gray("  [AutoExport] OFF"))
                safe_print(C.gray("  使い方: /autoexport <分> [保存先パス]"))
                safe_print(C.gray("  例:     /autoexport 5"))
                safe_print(C.gray("          /autoexport 10 C:/logs/session.md"))
            return

        # ── <分> [path]: 有効化 ───────────────────────────────────
        parts = arg.split(maxsplit=1)
        try:
            minutes = float(parts[0])
            if minutes <= 0:
                raise ValueError
        except ValueError:
            safe_print(C.red(f"  エラー: 分数を正の数で指定してください。例: /autoexport 5"))
            return

        interval_sec = int(minutes * 60)
        path = parts[1].strip() if len(parts) > 1 else str(Path(a.cwd) / "react_log.md")

        rl.start_auto_export(path, interval_sec)

        mins = interval_sec // 60
        secs = interval_sec % 60
        interval_str = f"{mins}分{secs}秒" if secs else f"{mins}分"
        safe_print(C.green(f"  [AutoExport] ON  —  {interval_str}ごとに自動保存"))
        safe_print(C.gray(f"  保存先: {path}"))
        safe_print(C.gray("  停止: /autoexport off"))

    # ── ログの定期自動エクスポート ───────────────
    # (既存のコマンド登録はそのまま)

    safe_print(C.cyan(f"  作業フォルダ: {agent.cwd}"))
    safe_print(C.gray(
        "  /mode plan|interactive でモード切り替え  "
        "·  /help で一覧  ·  exit で終了"
    ) + "\n")

    while True:
        try:
            mode_icon  = C.green("⚡") if current_mode == "interactive" else C.orange("📋")
            user_input = input(f"{mode_icon} {C.bold_green('❯')} ").strip()
        except (EOFError, KeyboardInterrupt):
            safe_print(C.gray("\n終了します。"))
            break

        if not user_input:
            continue
        if user_input.lower() in ("exit", "quit", "q"):
            safe_print(C.gray("終了します。"))
            break

        match = cmd_registry.route(user_input)
        if match:
            _, handler, args = match
            handler(agent, args)
            continue

        # ── モードに応じたルーティング ──────────────────────────
        if current_mode == "interactive":
            try:
                safe_print(f"\n{C.green_dim('┌─')} {C.bold_green('unimog')}")
                interactive_orch.run_react(user_input)
                safe_print(C.green_dim("└" + "─" * 20) + "\n")
            except Exception as e:
                safe_print(C.red(f"\n  ✗ {e}"))
                log.error({"event": "react_error", "error": str(e),
                           "traceback": traceback.format_exc()})
        else:  # plan
            _run_plan_ui(orchestrator, user_input)

    set_write_approval_handler(None)

def pipe_mode(agent: GeminiAgent, prompt: str):
    """
    パイプモード: PowerShell から
      python gemini_agent.py --prompt "質問文"
    のように呼び出す。結果を stdout に出力して終了。
    """
    try:
        response = agent.run(prompt)
        # UTF-8 で stdout に出力（PowerShellの文字化け対策）
        sys.stdout.buffer.write((response + "\n").encode("utf-8"))
        sys.stdout.buffer.flush()
        sys.exit(0)
    except Exception as e:
        msg = f"ERROR: {e}"
        sys.stderr.buffer.write((msg + "\n").encode("utf-8"))
        sys.stderr.buffer.flush()
        log.error({"event": "pipe_error", "error": str(e),
                   "traceback": traceback.format_exc()})
        sys.exit(1)

_UNIMOG_DONE_MARKER = "===UNIMOG_DONE==="

def auto_mode(
    interactive_orch: "InteractiveOrchestrator",
    prompt: str,
    orchestrator: "Optional[AgentOrchestrator]" = None,
):
    """
    MCP/Claude Code 連携用の自動実行モード。
    承認・介入を一切行わず、自律的にタスクを完結させる。
    prompt が "/plan " で始まる場合は Plan-and-Execute モードで実行する。
    orchestrator を渡すと __main__.py で構築済みのインスタンスを再利用する。
    """
    is_plan = prompt.startswith("/plan ")
    actual_prompt = prompt[6:] if is_plan else prompt

    interactive_orch._auto_mode = True   # セッション保存等のUIを抑制

    # ── on_done コールバック: 最終回答を即座に出力してマーカーを送る ──
    answer_sent = threading.Event()

    def on_answer(final_text: str):
        if answer_sent.is_set():
            return
        answer_sent.set()
        sys.stdout.write(_UNIMOG_DONE_MARKER + "\n")
        sys.stdout.flush()

    # ── 実行 ──────────────────────────────────────────────────
    error_holder: list = [None]

    try:
        if is_plan and orchestrator is not None:
            result = orchestrator.run_with_plan(actual_prompt)
            on_answer(result)
        else:
            result = interactive_orch.run_react(actual_prompt, on_done=on_answer)
            if not answer_sent.is_set():
                on_answer(result or "(応答なし)")
    except Exception as exc:
        error_holder[0] = exc
        if not answer_sent.is_set():
            on_answer(f"ERROR: {exc}")

    if not answer_sent.is_set():
        on_answer("(応答なし)")

    sys.exit(0 if error_holder[0] is None else 1)

def _run_plan_ui(orchestrator: "AgentOrchestrator", task: str):
    """/plan コマンドのハンドラ"""
    def on_plan(steps):
        safe_print(f"\n{C.green_dim('┌─')} {C.bold_green('実行計画')}")
        for s in steps:
            parallel_tag = C.orange(" [並列]") if s.parallel else ""
            safe_print(f"  {C.gray(f'Step {s.index}:')} {C.white(s.description)}{parallel_tag}")
        safe_print(C.green_dim("└" + "─" * 30))
        safe_print()

    def on_step(step):
        icons = {
            "running":  C.green("▶"),
            "done":     C.bold_green("✓"),
            "failed":   C.red("✗"),
            "retrying": C.yellow("↻"),
        }
        icon  = icons.get(step.status, " ")
        label = "" if step.index == 0 else C.gray(f"Step {step.index}: ")
        parallel_tag = C.orange(" ⚡") if getattr(step, "parallel", False) else ""
        safe_print(f"  {icon} {label}{step.description}{parallel_tag}", flush=True)

    def on_token(t: str):
        safe_print(C.purple(t), end="", flush=True)

    try:
        result = orchestrator.run_with_plan(
            task, on_plan=on_plan, on_step=on_step, on_token=on_token
        )
        safe_print(f"\n{C.green_dim('┌─')} {C.bold_green('完了')}")
        safe_print(render_markdown(result))
        safe_print(C.green_dim("└" + "─" * 20) + "\n")
    except Exception as e:
        safe_print(C.red(f"  ✗ {e}"))

