# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import json
import time
import random
import threading
import traceback
import re
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Any
from dataclasses import dataclass, field
from v4_modules.utils import safe_print, C, log, PipelineTypewriter, cache_tool_output
from v4_modules.config import PortContext, build_port_context, render_port_context
from v4_modules.agent import (GeminiAgent, AccountRotator, _stream_gemini_api,
                               _trim_messages_smart, _repair_message_sequence,
                               GeminiAPIError, RateLimitError, ServerError,
                               MAX_RETRIES, BASE_BACKOFF, MAX_BACKOFF, MAX_TOOL_ROUNDS,
                               _CACHEABLE_TOOLS, _print_write_diff)
from v4_modules.tools import ToolRegistry, tools
from v4_modules.autogit import AutoGit, ReactLog
from v4_modules.rag import LongTermMemory, SessionRAG, ProjectRAG, _compress_lesson, _parse_dt


def _format_lessons_for_injection(lessons: list[dict]) -> tuple[str, list[str]]:
    """
    教訓・セッションエントリのリストをプロンプト注入用にフォーマットする。
    表示も行い、(lessons_block, formatted_lines) を返す。
    """
    formatted_lines = []
    for e in lessons:
        e_type = e.get("type", "lesson")
        if e_type == "session":
            title    = e.get("title", "無題")
            summary  = e.get("summary", "")
            created  = _parse_dt(e.get("created_at", ""))
            days_ago = (datetime.now() - created).days
            line = f"[セッション: {title}] {summary} ({days_ago}日前)"
            formatted_lines.append(line[:150])
        else:
            text = e.get("lesson", "")
            line = f"[教訓] {_compress_lesson(text)}"
            formatted_lines.append(line[:100])
    for fl in formatted_lines[:5]:
        safe_print(C.mem(f"     • {fl}"), flush=True)
    lessons_block = "\n".join(formatted_lines[:5])
    return lessons_block, formatted_lines


def _extract_ps_status(result: str) -> str:
    """
    run_powershell の結果テキストからステータス行を抽出する。
    '[SUCCESS]' / '[FAILURE(ExitCode=N)]' / '[FAILURE(TIMEOUT)]' を返す。
    run_powershell を使っていないステップは空文字を返す。
    """
    for line in result.splitlines():
        line = line.strip()
        if line.startswith("[SUCCESS]") or line.startswith("[FAILURE"):
            return line
    return ""

@dataclass
class PlanStep:
    """1ステップの状態を保持するデータクラス"""
    index: int
    description: str
    status: str = "pending"       # pending / running / done / failed / retrying / skipped
    result: str = ""
    parallel: bool = False        # True: 前後の parallel=True ステップと並列実行可能
    label: str = ""               # ステップの名前ラベル（goto の参照先に使用）
    on_failure: str = "retry"     # 失敗時: "retry" | "skip" | "abort" | "goto:<label>"
    on_success: str = ""          # 成功時: "" (次へ) | "goto:<label>" | "abort"
    max_iterations: int = 0       # goto ループの最大回数（0=無制限だが安全上限 10 を適用）
    join_policy: str = "all"      # 並列バッチの結合条件: "all" | "any" | "first"

class WorkflowGraph:
    """
    PlanStep リストをグラフとして管理し、条件分岐・ジャンプ・共有ステートを制御する。

    エッジ遷移（on_failure / on_success）:
      "retry"       — リトライ（MAX_STEP_RETRY 回まで）
      "skip"        — スキップして次のステップへ
      "abort"       — ワークフロー全体を即座に中断
      "goto:<label>"— 指定ラベルのステップへジャンプ

    ループ防止:
      max_iterations > 0 のとき、同一ステップへの goto 回数が上限に達したら skip へ格下げ。
      未指定（0）の場合は安全上限 GOTO_HARD_LIMIT = 10 を適用。

    共有ステート:
      state dict にキー/値を保存し、各ステップのプロンプトへ自動注入する。
      ステップ結果内の [STATE: key=value] マーカーを自動パースして更新する。
    """

    GOTO_HARD_LIMIT = 10  # max_iterations=0 のときのハードリミット

    def __init__(self, steps: list[PlanStep]):
        self.steps = steps
        self.state: dict[str, str] = {}          # 共有ステート（スレッドセーフ書き込みは呼び出し元で制御）
        self._state_lock = threading.Lock()
        self._label_map: dict[str, int] = {      # label → step.index
            s.label: s.index for s in steps if s.label
        }
        self._goto_counts: dict[int, int] = {}   # step.index → goto された回数

    # ── 共有ステート ────────────────────────────────────────────

    def state_set(self, key: str, value: str) -> None:
        with self._state_lock:
            self.state[key] = value

    def state_get(self, key: str, default: str = "") -> str:
        return self.state.get(key, default)

    def state_as_text(self) -> str:
        """exec_prompt 注入用のテキスト表現"""
        if not self.state:
            return ""
        lines = "\n".join(f"  {k}: {v}" for k, v in self.state.items())
        return f"[共有ステート]\n{lines}"

    def parse_state_updates(self, result: str) -> None:
        """
        ステップ結果から [STATE: key=value] マーカーを検出して state を更新する。
        例: "[STATE: api_key=abc123]" → state["api_key"] = "abc123"
        """
        for m in re.finditer(r'\[STATE:\s*(\w+)\s*=\s*(.+?)\]', result):
            self.state_set(m.group(1).strip(), m.group(2).strip())

    # ── エッジ解決（共通ロジック） ──────────────────────────────

    def _resolve_directive(self, directive: str, step: PlanStep) -> tuple[str, Optional[int]]:
        """
        "retry" | "skip" | "abort" | "goto:<label>" を解釈して (action, goto_index) を返す。
        goto の場合はループカウンタをチェックし、上限超過なら "skip" に格下げ。
        """
        d = directive.strip().lower()
        if d in ("retry", ""):
            return "retry", None
        if d == "skip":
            return "skip", None
        if d == "abort":
            return "abort", None
        if d.startswith("goto:"):
            label = directive[5:].strip()
            idx = self._label_map.get(label)
            if idx is None:
                log.warning({"event": "workflow_goto_label_not_found", "label": label})
                return "skip", None
            # ループ上限チェック
            limit = step.max_iterations if step.max_iterations > 0 else self.GOTO_HARD_LIMIT
            count = self._goto_counts.get(step.index, 0) + 1
            if count > limit:
                safe_print(C.yellow(
                    f"  ⚠ Step {step.index} の goto ループが上限({limit}回)に達したためスキップ"
                ), flush=True)
                log.warning({"event": "workflow_goto_loop_limit",
                             "step": step.index, "limit": limit})
                return "skip", None
            self._goto_counts[step.index] = count
            return "goto", idx
        return "retry", None

    def resolve_failure(self, step: PlanStep) -> tuple[str, Optional[int]]:
        """失敗時の on_failure を解釈する"""
        return self._resolve_directive(step.on_failure, step)

    def resolve_success(self, step: PlanStep) -> tuple[str, Optional[int]]:
        """
        成功時の on_success を解釈する。
        空文字なら ("next", None) = 通常の次ステップへ進む。
        """
        if not step.on_success:
            return "next", None
        return self._resolve_directive(step.on_success, step)

    def summary(self) -> str:
        """実行後のステップ状態サマリー（ログ・表示用）"""
        return " → ".join(
            f"[{s.index}:{s.label or s.description[:20]} {s.status}]"
            for s in self.steps
        )

PLANNER_SYSTEM_PROMPT = """\
あなたはタスク計画専門のAIです。
ユーザーのリクエストを受け取り、具体的な実行ステップに分解してください。

# 絶対厳守ルール（最重要）
- **出力はJSONのみ**。前後・途中に一切のテキスト・説明・分析・思考を含めてはならない。
- 思考プロセス（「ユーザーは〜したい」「まず〜を確認する必要がある」等）をJSONの外に書くことは禁止。
- 分析・検討・理由の説明はすべて禁止。ステップの description に凝縮せよ。
- コードブロック（```json など）で囲まない。生のJSONをそのまま出力する。
- 出力の1文字目は必ず `{` でなければならない。

# 出力形式（全フィールドを必ず含めること）
{"steps":[{"label":"","description":"ステップ1の説明","parallel":false,"on_failure":"retry","on_success":"","max_iterations":0,"join_policy":"all"},{"label":"check","description":"確認ステップ","parallel":false,"on_failure":"goto:fallback","on_success":"goto:deploy","max_iterations":3,"join_policy":"all"},{"label":"fallback","description":"代替手段を試みる","parallel":false,"on_failure":"skip","on_success":"","max_iterations":0,"join_policy":"all"},{"label":"deploy","description":"デプロイ実行","parallel":false,"on_failure":"abort","on_success":"","max_iterations":0,"join_policy":"all"}]}

# parallel フィールドのルール
- parallel: true  → 前後の parallel:true ステップと同時並列実行される（互いに独立した作業）
- parallel: false → 前のステップ完了後に逐次実行（前のステップの結果が必要な作業）
- 連続する parallel:true のブロックが並列実行の単位になる
- 例: [false, true, true, false] → Step1 → (Step2 & Step3 同時) → Step4

# on_failure フィールドのルール（失敗時の遷移）
- "retry"        → デフォルト。失敗時にリトライ（最大2回）
- "skip"         → 失敗してもスキップして次のステップへ進む（オプション処理に使用）
- "abort"        → 失敗時にワークフロー全体を即座に中断（必須前提条件に使用）
- "goto:<label>" → 失敗時に label で指定したステップへジャンプ（代替フロー・リカバリに使用）

# on_success フィールドのルール（成功時の遷移）
- ""             → デフォルト。成功したら次のステップへ通常通り進む
- "goto:<label>" → 成功時に特定のステップへジャンプ（条件分岐に使用）
- "abort"        → 成功時にワークフローを終了（早期終了条件に使用）

# max_iterations フィールドのルール（ループ防止）
- 0              → デフォルト（安全上限10回が自動適用される）
- N (1以上)      → このステップへの goto が N 回を超えたら自動的に skip へ格下げ
- goto ループを使う場合は必ず設定すること（例: max_iterations: 3）

# join_policy フィールドのルール（並列バッチの結合条件）
- "all"          → デフォルト。全並列ステップの完了を待つ
- "any"          → いずれか1つが成功した時点で残りをスキップして次へ進む
- "first"        → 成功/失敗を問わず最初に完了したステップの結果で次へ進む
- 同一並列バッチ内の全ステップに同じ join_policy を設定すること

# label フィールドのルール
- goto のジャンプ先となるステップには一意のラベルをつける（例: "fallback", "cleanup", "deploy"）
- ジャンプ先でないステップは label を空文字 "" にする

# 共有ステートのルール
- ステップ間で値を渡す必要がある場合、結果に [STATE: key=value] を含めるよう description に指示できる
- 例: description に「取得したAPIキーを [STATE: api_key=<値>] の形式で出力すること」と記載する

# その他のルール
- ステップ数は3〜20個（単純なタスクは少なく、複雑なタスクは多く）
- 各ステップの description は具体的かつ実行可能な内容にする（例: 「PowerShellでXXXを実行」）
- description に分析過程・背景説明を含めない。実行する操作のみを記述する。
"""

POWERSHELL_EXECUTOR_GUIDANCE = """\

[PowerShell実行ガイドライン（必須遵守）]
- **PowerShellコマンドは必ず自分で run_powershell ツールを使って実行すること。ユーザーに「実行してください」と依頼してはならない。**
- run_powershell を呼ぶときは working_directory に現在の作業フォルダのフルパスを必ず指定する。
- コマンド結果の先頭が [SUCCESS] なら成功、[FAILURE...] なら失敗。FAILUREは必ずリトライまたは代替手段を取ること。
- ファイルパスはバックスラッシュ（\\）またはJoin-Pathを使うこと。スラッシュは予期しない動作を起こす場合がある。
- 複数行コマンドはヒアストリング(@' ... '@)またはセミコロン区切りで1回のrun_powershellにまとめる。
- 文字コードはrun_powershellが自動でUTF-8に設定する。追加のchcp指定は不要。
- エラー発生時は $Error[0].Exception.Message で詳細を取得して原因を特定してから対処する。
- 変数は同一コマンド内でのみ有効。ステップをまたぐ場合はファイルやレジストリ経由で値を渡す。

[ツール出力の制限（必須遵守）]
- すべてのツール出力は8000文字を超えると自動的にメモリにキャッシュされ、先頭8000文字と cache_key が返される。
- 続きを読む場合は read_tool_cache(cache_key="...", offset=8000) を呼び出す。
- ファイル読み取りは read_file の offset で8000文字ずつ分割して読むこと。
"""

REVIEWER_SYSTEM_PROMPT = """\
あなたはタスク検証専門のAIです。
「ステップの目標」と「実行結果」を比較し、目標が達成されたか判定してください。

出力形式（必ずこのJSON形式のみで出力してください）:
{
  "ok": true,
  "reason": "判定理由を1文で"
}

ルール:
- ok=true: 目標が達成された、または部分的に達成されエラーなし
- ok=false: エラーが発生した、または目標が明らかに未達成
- JSONのみを出力し、前後に説明文を加えない
"""

REFLECTOR_SYSTEM_PROMPT = """\
あなたはタスク完了検証の専門家です。
read_file や list_directory ツールを使って実際にファイルや結果を確認し、
クライアントの要望が完全・正確に達成されているか判定してください。

検証手順:
1. タスクで作成・変更・実行されたはずのファイルやリソースを read_file / list_directory で実際に確認する
2. 期待する内容と一致しているか検証する
3. 確認結果に基づいて判定する

最終出力形式（検証完了後に必ずこのJSON形式のみで出力してください）:
{
  "ok": true,
  "issue": "問題がある場合の具体的な修正指示（ok=true の場合は空文字）"
}

ルール:
- ok=true: ファイル内容などを実際に確認し、タスクが完全・正確に達成されたと確認できた
- ok=false: 実際に確認した結果、エラー・未達成・内容の誤りがある
- issue: ok=false の場合のみ、Executor が実行できる具体的な修正内容を記述
- 推測で判定しない。必ずツールで確認してから判定する
- 最終出力はJSONのみ。前後に説明文を加えない
"""

REACT_SYSTEM_PROMPT = """
# Interactive (ReAct) モード 追加指示

## 言語（最重要）
- **すべての出力を日本語で行う**（Thought・最終回答・質問・説明すべて）
- English output is strictly prohibited. Always respond in Japanese.

## 思考の構造化 (Chain of Thought)
行動を起こす前、または最終回答を出す前に、必ず以下のタグを使用して思考を構造化してください。

1. **<thinking>** タグ:
   - 現状の分析（何が起きていて、何が必要か）
   - 不明点の特定
   - エラーが出た場合はその原因の深掘り
   - プロジェクト構造が不明な場合は `get_repo_map` を使用する計画を立てる

2. **<plan>** タグ:
   - 実行する具体的なステップ
   - 使用するツールとその引数の想定

例:
<thinking>
ユーザーは○○の機能を修正したいと考えている。
まず現状のコードを確認する必要があるが、プロジェクトの全体像が不明。
</thinking>
<plan>
1. `get_repo_map` でプロジェクト構造を確認する。
2. 該当するファイルを `read_file` で読み込む。
</plan>

Thought: get_repo_map を実行して構造を確認します。

## 基本フロー
各ターンで「<thinking><plan> + テキスト（Thought）+ ツール呼び出し」または「<thinking> + テキスト（最終回答）のみ」を出力する。

### ツールを使う場合
1. 上記タグで思考を構造化した後、状況と方針をテキストで簡潔に述べる（Thought: で始める）
2. 続けてツールを functionCall で呼び出す
3. ツール結果（Observation）を受け取って次のアクションを決める
4. すべて完了したら最終回答をテキストで出力する

### ツールが不要な場合
- 一般的な質問・説明・計算は直接テキストで答える
- ファイル操作・コマンド実行・情報検索・不確かな事実のみツールを使う

## 重要な作業ルール
- **プロジェクト構造が不明な場合は、まず `get_repo_map` で全体像を把握すること。**
- **ファイルを編集・上書きする前に必ず read_file で現在の内容を確認する**
- エラーが出たら内容を分析して原因を特定し、対処策を実行する
- 複数の独立した読み取り操作は同時に呼び出す（並列実行で高速化）
- タスク完了時は「Thought: 完了。」で締めくくり、結果を簡潔にまとめる

## ツール使用の禁止事項
- ツール呼び出しをテキスト内に文字列として書かない（例: 「list_directory を使います」と書くだけで終わらせない）
- 必ず functionCall（API呼び出し）で実行する
- 確認せずにファイルを上書き・削除しない
- 推測だけで重要なファイル操作を行わない

## 【最重要】タスク完了と停止ルール

### タスクが完了したら即座に停止する
- ユーザーが依頼したことをすべて実行したら、**その時点で最終回答を出力して終了する**
- 「他にも直すべき点があるかもしれない」と考えてはならない
- 依頼されていない改善・最適化・リファクタリングを自発的に行ってはならない

### 「もう一つ直そうか」思考パターンの禁止
以下のような内部ループに入ってはならない：
  × 「この問題も修正すべきか？」→「いや、やめておこう」→「でも直した方が良いかも」→（繰り返し）
上記に気づいたら即座に停止し、最終回答を出力する。

### オプション的な問題を見つけた場合
- 依頼の範囲外の問題を発見した場合は、修正せず「メモ: ～という問題も見つかりました。必要であれば別途対応します」と最終回答に一言添えて終了する
- 直すかどうか自分で判断しない。必ずユーザーに委ねる。

### 完了判定チェックリスト（内部確認用）
最終回答を出す前に確認：
1. ユーザーが明示的に依頼したことをすべて実行したか？ → Yes なら終了
2. まだ未完了のステップがあるか？ → No なら終了
3. 次のアクションが「依頼範囲外の改善」だけか？ → Yes なら終了

## 利用可能なツール一覧（参考）
read_file, read_tool_cache, write_file, edit_file, patch_file, append_file,
create_directory, move_file, copy_file, delete_file,
list_directory, glob, search_files, get_repo_map,
run_powershell, web_search, fetch_webpage
"""

class AgentOrchestrator:
    """
    Plan-and-Execute マルチエージェント オーケストレーター。

    構成:
      Planner  — タスクをステップに分解（ツールなし・thinking OFF）
      Executor — 各ステップをツールで実行（既存 GeminiAgent と同等）
      Reviewer — 結果を検証（ツールなし・thinking OFF）

    Token Bucket 連携:
      - 全エージェントが同じ AccountRotator を共有
      - Reviewer は can_afford_reviewer() が True のときだけ実行
      - wait_to_start() でタスク開始前に RPM 残量を確認・自動待機
    """

    MAX_STEP_RETRY = 2  # 1ステップあたりの最大リトライ回数

    def __init__(self, rotator: "AccountRotator", tool_registry: "ToolRegistry",
                 executor: Optional["GeminiAgent"] = None,
                 long_term_memory: Optional["LongTermMemory"] = None):
        self.rotator = rotator
        self.tool_registry = tool_registry  # 並列 Executor 生成に使用
        self.long_term_memory = long_term_memory

        # Planner: ツールなし、軽量、JSON 出力を API レベルで強制
        self.planner = GeminiAgent(rotator, ToolRegistry())
        self.planner.set_system_prompt(PLANNER_SYSTEM_PROMPT)
        self.planner.set_thinking(False, silent=True)
        self.planner.json_mode = True  # response_mime_type: application/json → JSON 崩れを防止

        # Executor: 外部から渡されたインスタンスを使う（main の agent と同一にしてセッション履歴を共有）
        self.executor = executor if executor is not None else GeminiAgent(rotator, tool_registry)

        # Reflector: 全体タスク完了後の最終検証（read_file・list_directory のみ許可）
        verify_registry = ToolRegistry()
        for spec_name in ("read_file", "list_directory"):
            # グローバル tools レジストリから読み取り系ツールだけを複製
            verify_registry.copy_tool(spec_name, tool_registry)
        self.reflector = GeminiAgent(rotator, verify_registry)
        self.reflector.set_system_prompt(REFLECTOR_SYSTEM_PROMPT)
        self.reflector.set_thinking(False, silent=True)

    def set_executor_system_prompt(self, prompt: str):
        self.executor.set_system_prompt(prompt)

    def _make_executor_agent(self) -> "GeminiAgent":
        """並列実行用に独立した Executor エージェントを生成（状態を共有しない）"""
        a = GeminiAgent(self.rotator, self.tool_registry)
        a.set_system_prompt(self.executor.system_prompt or "")
        a.set_thinking(self.executor.thinking_enabled, silent=True)
        a.cwd = self.executor.cwd
        # RAG ストアを共有（インデックスの重複を防ぐ）
        a._project_rag = self.executor._project_rag
        a._session_rag = self.executor._session_rag
        return a

    def _parse_plan(self, text: str) -> list[dict]:
        """
        Planner の出力からステップリストを抽出。
        Returns: [{"description": str, "parallel": bool}, ...]

        モデルがJSONの前後にテキストを混入させても正しく抽出できるよう、
        brace-matching で全 { ... } 候補を列挙し、
        json.loads が成功して "steps" 配列を持つ最初のものを採用する。
        """
        # ── brace-matching で完全な { ... } ブロックを全て列挙 ──────────
        def _iter_json_candidates(s: str):
            """テキスト中の全 { ... } ブロックをネスト対応で順に yield する"""
            i = 0
            while i < len(s):
                if s[i] == '{':
                    depth = 0
                    start = i
                    for j in range(i, len(s)):
                        if s[j] == '{':
                            depth += 1
                        elif s[j] == '}':
                            depth -= 1
                            if depth == 0:
                                yield s[start:j + 1]
                                i = j  # 次の検索はこのブロックの直後から
                                break
                i += 1

        for candidate in _iter_json_candidates(text):
            try:
                data = json.loads(candidate)
                steps = data.get("steps", [])
                if steps and isinstance(steps, list) and len(steps) > 0:
                    result = []
                    for s in steps[:20]:
                        if isinstance(s, dict):
                            result.append({
                                "description":  str(s.get("description", s)),
                                "parallel":     bool(s.get("parallel", False)),
                                "label":        str(s.get("label", "")),
                                "on_failure":   str(s.get("on_failure", "retry")),
                                "on_success":   str(s.get("on_success", "")),
                                "max_iterations": int(s.get("max_iterations", 0)),
                                "join_policy":  str(s.get("join_policy", "all")),
                            })
                        else:
                            result.append({
                                "description": str(s), "parallel": False,
                                "label": "", "on_failure": "retry",
                                "on_success": "", "max_iterations": 0, "join_policy": "all",
                            })
                    return result
            except json.JSONDecodeError:
                continue  # このブロックは無効 → 次の候補へ

        log.warning({"event": "plan_json_not_found", "text_preview": text[:200]})

        # フォールバック: 行分割（parallel=False で逐次実行）
        # "Step N:" や箇条書き記号を除去して description のみ残す
        cleaned = []
        for line in text.splitlines():
            line = line.strip()
            if not line:
                continue
            # "Step 1: ..." や "* ..." や "- ..." の先頭記号を除去
            line = re.sub(r'^(Step\s*\d+\s*[:：]\s*|\*\s+|-\s+|\d+\.\s+)', '', line)
            if line:
                cleaned.append(line)
        log.warning({"event": "plan_fallback_to_lines", "line_count": len(cleaned)})
        return [{"description": l, "parallel": False} for l in cleaned[:20]] or \
               [{"description": text, "parallel": False}]

    def _parse_review(self, text: str) -> tuple[bool, str]:
        """Reviewer の出力から ok/reason を抽出"""
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                return bool(data.get("ok", True)), data.get("reason", "")
            except json.JSONDecodeError:
                pass
        # フォールバック: エラー文字列を探す
        lower = text.lower()
        if "false" in lower or "失敗" in lower or "エラー" in lower:
            return False, text[:100]
        return True, ""

    @staticmethod
    def _build_review_prompt(description: str, result: str, ps_status: str) -> str:
        """
        Reviewer に渡す構造化プロンプトを生成する。
        ps_status: _extract_ps_status() の戻り値（空文字 = PSコマンドなし）
        """
        lines = [f"ステップの目標: {description}"]
        if ps_status:
            is_fail = ps_status.startswith("[FAILURE")
            lines.append(f"PowerShell実行ステータス: {ps_status}")
            if is_fail:
                lines.append("※ FAILUREはコマンド失敗を意味します。ok=false を強く推奨します。")
        lines.append(f"実行結果（全文）:\n{result[:2000]}")
        return "\n".join(lines)

    def _make_reviewer(self) -> "GeminiAgent":
        """軽量な Reviewer エージェントを生成（ツールなし・thinking OFF）"""
        r = GeminiAgent(self.rotator, ToolRegistry())
        r.set_system_prompt(REVIEWER_SYSTEM_PROMPT)
        r.set_thinking(False, silent=True)
        # RAG ストアを共有（インデックスの重複を防ぐ）
        r._project_rag = self.executor._project_rag
        r._session_rag = self.executor._session_rag
        return r

    def _execute_step(
        self,
        step: "PlanStep",
        all_steps: list["PlanStep"],
        user_message: str,
        agent: "GeminiAgent",
        on_step=None,
        reviewer_pool: Optional[ThreadPoolExecutor] = None,
        on_token=None,
        workflow: Optional["WorkflowGraph"] = None,
    ) -> "Optional[Future]":
        """
        単一ステップを実行。

        reviewer_pool が渡された場合（逐次ステップ）:
            Reviewer を非同期投入して即座に次のステップへ進む（オーバーラップ実行）。
            Future を返すので呼び出し元がまとめて結果を収集する。

        reviewer_pool が None の場合（並列ステップ内）:
            Reviewer を同期実行してリトライも行う（従来動作）。

        workflow が渡された場合:
            共有ステートをプロンプトに注入し、結果から [STATE: key=value] を自動パースする。
        """
        step.status = "running"
        if on_step:
            on_step(step)

        # 完了済みステップの結果を直近3件まで注入（コンテキスト節約）
        prior_done = [s for s in all_steps if s.index < step.index and s.result]
        if prior_done:
            prior_text = "\n[完了済みステップの結果（参考）]\n" + "\n".join(
                f"  Step {s.index} 「{s.description[:60]}」→ {s.result[:300]}"
                for s in prior_done[-3:]
            ) + "\n"
        else:
            prior_text = ""

        # 共有ステートをプロンプトに注入
        state_text = ("\n" + workflow.state_as_text()) if workflow and workflow.state else ""

        # ステート書き込み方法をヒントとして追加
        state_hint = (
            "\n値を次ステップへ渡す場合は結果に [STATE: key=value] を含めてください。"
            if workflow is not None else ""
        )

        exec_prompt = (
            f"[全体タスク] {user_message}\n"
            f"{prior_text}"
            f"{state_text}\n"
            f"[現在のステップ {step.index}/{len(all_steps)}] {step.description}\n"
            f"このステップのみを実行してください。{state_hint}"
        )
        step.result = agent.run_stream(exec_prompt, callback=on_token)

        # 共有ステートを結果からパース・更新
        if workflow is not None:
            workflow.parse_state_updates(step.result)
        step.status = "done"
        if on_step:
            on_step(step)

        if not self.rotator.can_afford_reviewer():
            return None

        if reviewer_pool is not None:
            # ── 非同期 Reviewer（逐次ステップ用）────────────────────
            # 次のステップとオーバーラップして実行。結果は run_with_plan が収集。
            desc    = step.description
            result  = step.result
            parse   = self._parse_review
            make_r  = self._make_reviewer
            ps_st   = _extract_ps_status(result)
            def _async_review():
                raw = make_r().run_stream(
                    self._build_review_prompt(desc, result, ps_st),
                    callback=lambda t: safe_print(C.purple(t), end="", flush=True),
                )
                return parse(raw)
            return reviewer_pool.submit(_async_review)
        else:
            # ── 同期 Reviewer（並列ステップ用）+ リトライ────────────
            retry = 0
            while retry < self.MAX_STEP_RETRY:
                review_raw = self._make_reviewer().run_stream(
                    self._build_review_prompt(
                        step.description, step.result,
                        _extract_ps_status(step.result)
                    ),
                    callback=lambda t: safe_print(C.purple(t), end="", flush=True),
                )
                ok, reason = self._parse_review(review_raw)
                if ok:
                    break
                retry += 1
                step.status = "retrying"
                log.info({"event": "step_retry", "step": step.index,
                          "reason": reason, "retry": retry})
                if on_step:
                    on_step(step)
                step.result = agent.run_stream(exec_prompt, callback=on_token)
                step.status = "done"
                if on_step:
                    on_step(step)
            return None

    def _execute_steps_parallel(
        self,
        parallel_steps: list["PlanStep"],
        all_steps: list["PlanStep"],
        user_message: str,
        on_step=None,
        on_token=None,
        workflow: Optional["WorkflowGraph"] = None,
    ) -> None:
        """
        独立した複数ステップを ThreadPoolExecutor で並列実行。
        join_policy に応じて結合条件を制御する:
          "all"   — 全ステップ完了を待つ（デフォルト）
          "any"   — いずれか1つ成功した時点で残りをキャンセルして次へ進む
          "first" — 成功/失敗を問わず最初に完了したステップの結果で次へ進む
        """
        n = len(parallel_steps)
        join_policy = parallel_steps[0].join_policy if parallel_steps else "all"
        safe_print(C.orange(f"  ⚡ {n} ステップを並列実行 [join={join_policy}]"), flush=True)
        log.info({"event": "parallel_start",
                  "steps": [s.index for s in parallel_steps], "join_policy": join_policy})

        agents = [self._make_executor_agent() for _ in range(n)]
        done_event = threading.Event()  # "any"/"first" 用: 条件達成を通知

        def _run_one(step: "PlanStep", agent: "GeminiAgent") -> None:
            if done_event.is_set():
                step.status = "skipped"
                if on_step:
                    on_step(step)
                return
            try:
                self._execute_step(step, all_steps, user_message, agent, on_step,
                                   None, None, workflow=workflow)
            except Exception as e:
                step.status = "failed"
                step.result = f"並列実行エラー: {e}"
                log.error({"event": "parallel_step_error",
                           "step": step.index, "error": str(e)})
                if on_step:
                    on_step(step)

        with ThreadPoolExecutor(max_workers=n) as pool:
            futures = {
                pool.submit(_run_one, step, agent): step
                for step, agent in zip(parallel_steps, agents)
            }

            if join_policy == "all":
                for future in as_completed(futures):
                    try:
                        future.result()
                    except Exception:
                        pass  # エラーは _run_one 内で処理済み

            elif join_policy in ("any", "first"):
                for future in as_completed(futures):
                    step = futures[future]
                    try:
                        future.result()
                    except Exception:
                        pass
                    condition_met = (
                        join_policy == "first" or
                        (join_policy == "any" and step.status == "done")
                    )
                    if condition_met and not done_event.is_set():
                        done_event.set()
                        safe_print(C.orange(
                            f"  ✓ join_policy={join_policy}: Step {step.index} 完了 → 残りをスキップ"
                        ), flush=True)
                        log.info({"event": "parallel_join_triggered",
                                  "policy": join_policy, "winner": step.index})
                # done_event 未設定のまま全完了した場合はそのまま（全て失敗など）

    @staticmethod
    def _group_into_batches(steps: list["PlanStep"]) -> list[list["PlanStep"]]:
        """
        連続する parallel=True ステップをグループ化して実行バッチを生成する。
        例: [F, T, T, F] → [[F], [T, T], [F]]
        """
        batches: list[list[PlanStep]] = []
        current: list[PlanStep] = []
        for step in steps:
            if step.parallel:
                current.append(step)
            else:
                if current:
                    batches.append(current)
                    current = []
                batches.append([step])
        if current:
            batches.append(current)
        return batches

    def _parse_reflection(self, text: str) -> tuple[bool, str, list[str], list[str]]:
        """Reflector の出力から ok/issue/helpful/unhelpful を抽出"""
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if match:
            try:
                data = json.loads(match.group())
                return (
                    bool(data.get("ok", True)),
                    data.get("issue", ""),
                    data.get("helpful_lessons", []),
                    data.get("unhelpful_lessons", [])
                )
            except json.JSONDecodeError:
                pass
        lower = text.lower()
        if "修正" in lower or "問題" in lower or "エラー" in lower or "失敗" in lower:
            return False, text[:300], [], []
        return True, "", [], []

    def _reflect_and_correct(
        self,
        user_message: str,
        final_result: str,
        steps: list["PlanStep"],
        injected_lessons: Optional[list[str]] = None,
        on_token=None,
    ) -> tuple[str, list[str], list[str]]:
        """
        Reflection Loop: 最終結果を振り返り、不備があれば Executor で修正する。
        併せて、注入された教訓の有効性も判定する。
        """
        self.reflector.clear_history()
        self.reflector.cwd = self.executor.cwd  # 作業フォルダを同期
        step_summary = "\n".join(
            f"  Step {s.index} ({s.status}): {s.description}" for s in steps
        )
        
        lesson_context = ""
        if injected_lessons:
            list_str = "\n".join(f"- {l}" for l in injected_lessons)
            lesson_context = f"\n[注入された過去の教訓]\n{list_str}\n"

        prompt = (
            f"[タスク] {user_message}\n\n"
            f"[作業フォルダ] {self.executor.cwd}\n\n"
            f"[実行ステップ]\n{step_summary}\n"
            f"{lesson_context}\n"
            f"[Executorの最終報告]\n{final_result[:2000]}\n\n"
            f"1. read_file や list_directory で実際にファイルを確認し、タスクが正確に完了しているか検証してください。\n"
            f"2. 注入された各教訓が、今回のタスク解決に「実際に役立ったか」を判定してください。\n\n"
            f"出力形式(JSONのみ):\n"
            f"{{\n"
            f"  \"ok\": true/false,\n"
            f"  \"issue\": \"問題がある場合の修正指示\",\n"
            f"  \"helpful_lessons\": [\"役立った教訓の本文\"],\n"
            f"  \"unhelpful_lessons\": [\"役立たなかった、または無関係だった教訓の本文\"]\n"
            f"}}"
        )

        reflection_raw = self.reflector.run_stream(
            prompt,
            callback=on_token or (lambda t: safe_print(C.purple(t), end="", flush=True)),
        )
        ok, issue, helpful, unhelpful = self._parse_reflection(reflection_raw)
        
        if not ok and issue:
            log.info({"event": "reflection_correction", "issue": issue[:120]})
            safe_print(C.yellow(f"  ↻ Reflection: 修正が必要です → {issue[:80]}"), flush=True)
            corrected = self.executor.run_stream(
                f"[Reflection による修正指示]\n{issue}\n\n"
                f"上記の問題を修正して最終結果を出力してください。",
                callback=on_token,
            )
            safe_print(C.bold_green("  ✓ 修正完了"), flush=True)
            return corrected, helpful, unhelpful
        else:
            safe_print(C.bold_green("  ✓ Reflection: タスク完了を確認"), flush=True)
        
        return final_result, helpful, unhelpful

    def run_with_plan(
            self,
            user_message: str,
            on_plan=None,
            on_step=None,
            on_token=None,
        ) -> str:
            """
            Plan-and-Execute + 並列実行 + Reflection Loop のメインループ。
            """
            injected_lesson_texts = []
            # ── 0. 長期記憶から関連教訓をRAG注入 ────────────────────────
            if self.long_term_memory and self.rotator.accounts:
                try:
                    _api_key = self.rotator.pick()[0].api_key
                    _lessons = self.long_term_memory.retrieve_relevant_lessons(
                        user_message, _api_key
                    )
                    if _lessons:
                        safe_print(C.bold_mem(
                            f"  🧠 記憶から {len(_lessons)} 件をロードしました"
                        ), flush=True)
                        lessons_block, _ = _format_lessons_for_injection(_lessons)
                        user_message = f"[過去の記憶]\n{lessons_block}\n\n" + user_message
                except Exception as _e:
                    log.warning({"event": "rag_retrieve_error_plan", "error": str(_e)})

            # ── 1. Planner 用トークン確認 ──────────────────────────────
            wait = self.rotator.wait_to_start(1)
            if wait > 0.5:
                log.info({"event": "plan_wait", "wait_sec": round(wait, 1)})
                if on_step:
                    dummy = PlanStep(0, f"トークン補充待ち: {wait:.1f}秒", "running")
                    on_step(dummy)
                time.sleep(wait)

            # ── 2. Planner でステップ作成 ──────────────────────────────
            # clear_history() を呼ばない → 過去の(prompt, JSON)ペアが履歴に残る
            # モデルは「自分の応答は常にJSON」と学習し、JSON崩れを自然に防ぐ
            # 履歴上限: 直近4タスク分（8ターン）に制限してトークン肥大を防ぐ
            MAX_PLANNER_HISTORY = 8
            if len(self.planner.conversation) > MAX_PLANNER_HISTORY:
                self.planner.conversation = self.planner.conversation[-MAX_PLANNER_HISTORY:]

            tool_names = ", ".join(
                t["name"] for t in self.tool_registry.get_specs()
            ) if self.tool_registry.get_specs() else "run_powershell, read_file, write_file, edit_file, search_files, web_search"
            plan_prompt = (
                "以下のタスクを実行ステップのJSONに分解してください。\n\n"
                "【出力ルール・絶対厳守】\n"
                "1. 出力の1文字目は { でなければならない\n"
                '2. 形式: {"steps":[{"description":"操作内容","parallel":false}, ...]}\n'
                "3. descriptionには分析・説明を書かず、実行する操作だけを書く\n"
                "4. parallel: true=前後のtrue同士を並列 / false=逐次\n"
                "5. JSON以外のテキスト・コードブロック・説明は一切出力禁止\n\n"
                f"[OS] Windows 10 / PowerShell\n"
                f"[作業フォルダ] {self.executor.cwd}\n"
                f"[ツール] {tool_names}\n\n"
                f"[タスク]\n{user_message}"
            )
            plan_raw = self.planner.run_stream(
                plan_prompt,
                callback=lambda t: safe_print(C.purple(t), end="", flush=True),
            )
            steps_desc = self._parse_plan(plan_raw)

            if not steps_desc and len(self.planner.conversation) >= 2:
                self.planner.conversation = self.planner.conversation[:-2]
                log.warning({"event": "planner_history_rollback"})

            steps = [
                PlanStep(
                    index=i + 1,
                    description=d["description"],
                    parallel=d["parallel"],
                    label=d.get("label", ""),
                    on_failure=d.get("on_failure", "retry"),
                    on_success=d.get("on_success", ""),
                    max_iterations=int(d.get("max_iterations", 0)),
                    join_policy=d.get("join_policy", "all"),
                )
                for i, d in enumerate(steps_desc)
            ]
            workflow = WorkflowGraph(steps)

            if on_plan:
                on_plan(steps)

            # ── 3. 実際のステップ数で再チェック ────────────────────────
            wait2 = self.rotator.wait_to_start(len(steps))
            if wait2 > 0.5:
                log.info({"event": "plan_wait2", "wait_sec": round(wait2, 1)})
                time.sleep(wait2)

            # ── 4. Executor + Reviewer ループ（並列バッチ + Reviewerオーバーラップ）──
            # ※ clear_history() を呼ばない → セッション中の会話履歴を引き継ぐ
            # Plan開始前に強制コンパクト: Executor初回コールのペイロード肥大を防ぐ
            self.executor._compact_if_needed()
            self.executor.start_task(user_message)
            results: list[str] = []

            batches = self._group_into_batches(steps)

            # 逐次ステップの Reviewer を前ステップ完了後に同期待機するプール
            n_accounts = len(self.rotator.accounts)

            workflow_aborted = False  # abort が発生したらループを抜ける
            goto_index: Optional[int] = None  # goto:<label> で次に実行するステップ index

            def _handle_reviewer_result(prev_step: "PlanStep", ok: bool, reason: str) -> Optional[int]:
                """
                Reviewer 結果を受けて on_failure / on_success を解決し goto_index を返す。
                workflow_aborted が必要な場合は None を返して呼び出し元が判断できるよう
                nonlocal は使わず戻り値で制御する。
                Returns: goto_target_index | -1 (abort) | None (continue)
                """
                if not ok:
                    safe_print(C.yellow(
                        f"  ↻ Reviewer(Step {prev_step.index}): {reason[:80]}"
                    ), flush=True)
                    action, jump_to = workflow.resolve_failure(prev_step)
                    if action == "abort":
                        safe_print(C.red(
                            f"  ✗ Step {prev_step.index}: on_failure=abort → ワークフロー中断"
                        ), flush=True)
                        log.info({"event": "workflow_aborted", "step": prev_step.index})
                        return -1  # 中断シグナル
                    if action == "skip":
                        prev_step.status = "skipped"
                        safe_print(C.yellow(
                            f"  ⏭  Step {prev_step.index} スキップ (on_failure=skip)"
                        ), flush=True)
                        if on_step:
                            on_step(prev_step)
                    elif action == "goto" and jump_to is not None:
                        safe_print(C.orange(
                            f"  ↷  Step {prev_step.index} 失敗 → Step {jump_to} へジャンプ"
                        ), flush=True)
                        log.info({"event": "workflow_goto_failure",
                                  "from": prev_step.index, "to": jump_to})
                        return jump_to  # goto シグナル
                    else:
                        # retry
                        for _ in range(self.MAX_STEP_RETRY):
                            prev_step.status = "retrying"
                            if on_step:
                                on_step(prev_step)
                            prev_step.result = self.executor.run_stream(
                                f"[Reviewer からのリトライ指示]\n{reason}\n\n"
                                f"[全体タスク] {user_message}\n"
                                f"[再実行ステップ] {prev_step.description}\n"
                                f"問題を修正して再度実行してください。",
                                callback=on_token,
                            )
                            if workflow:
                                workflow.parse_state_updates(prev_step.result)
                            prev_step.status = "done"
                            if on_step:
                                on_step(prev_step)
                            re_raw = self._make_reviewer().run_stream(
                                self._build_review_prompt(
                                    prev_step.description, prev_step.result,
                                    _extract_ps_status(prev_step.result)
                                ),
                                callback=lambda t: safe_print(C.purple(t), end="", flush=True),
                            )
                            ok2, _ = self._parse_review(re_raw)
                            if ok2:
                                break
                else:
                    # ── 成功時の on_success を処理 ──────────────────
                    s_action, s_jump = workflow.resolve_success(prev_step)
                    if s_action == "abort":
                        safe_print(C.red(
                            f"  ✗ Step {prev_step.index}: on_success=abort → ワークフロー中断"
                        ), flush=True)
                        return -1
                    if s_action == "goto" and s_jump is not None:
                        safe_print(C.orange(
                            f"  ↷  Step {prev_step.index} 成功 → Step {s_jump} へジャンプ (on_success)"
                        ), flush=True)
                        log.info({"event": "workflow_goto_success",
                                  "from": prev_step.index, "to": s_jump})
                        return s_jump
                return None  # 通常継続

            def _do_goto(target_idx: int) -> None:
                """goto_index への再実行（pending は呼び出し元が事前クリアすること）"""
                nonlocal workflow_aborted, goto_index
                found = next(
                    (j for j, b in enumerate(batches) if any(s.index == target_idx for s in b)),
                    None
                )
                if found is None:
                    return
                for remaining_bi in range(found, len(batches)):
                    if workflow_aborted:
                        break
                    batch = batches[remaining_bi]
                    if len(batch) == 1:
                        future = self._execute_step(
                            batch[0], steps, user_message,
                            self.executor, on_step,
                            reviewer_pool=reviewer_pool,
                            on_token=on_token,
                            workflow=workflow,
                        )
                        # goto 内では pending を使わず同期的に Reviewer を待つ
                        if future is not None:
                            try:
                                ok_g, reason_g = future.result()
                                sig = _handle_reviewer_result(batch[0], ok_g, reason_g)
                                if sig == -1:
                                    workflow_aborted = True
                                    return
                                if isinstance(sig, int):
                                    goto_index = sig
                                    return
                            except Exception as eg:
                                log.warning({"event": "goto_reviewer_error", "error": str(eg)})
                    else:
                        self._execute_steps_parallel(
                            batch, steps, user_message, on_step, workflow=workflow
                        )

            with ThreadPoolExecutor(max_workers=n_accounts) as reviewer_pool:
                pending: Optional[tuple["PlanStep", "Future"]] = None  # 直前の逐次Reviewer

                batch_iter = iter(range(len(batches)))
                for bi in batch_iter:
                    if workflow_aborted:
                        break

                    # goto が発生していた場合: 対象インデックス以降のバッチへ再実行
                    if goto_index is not None:
                        target_idx = goto_index
                        goto_index = None
                        pending = None
                        _do_goto(target_idx)
                        if workflow_aborted:
                            break
                        if goto_index is not None:
                            continue  # 再度 goto が発生した場合は次ループで処理
                        break  # _do_goto が残りバッチを消化したのでメインループ終了

                    batch = batches[bi]

                    # ── 前の逐次ステップの Reviewer 結果を待ってから次を開始 ──
                    if pending is not None:
                        prev_step, prev_future = pending
                        pending = None
                        try:
                            ok, reason = prev_future.result()
                            sig = _handle_reviewer_result(prev_step, ok, reason)
                            if sig == -1:
                                workflow_aborted = True
                                break
                            if isinstance(sig, int):
                                goto_index = sig
                        except Exception as e:
                            log.warning({"event": "reviewer_sync_error", "error": str(e)})

                    if workflow_aborted:
                        break

                    if len(batch) == 1:
                        # 逐次実行: Reviewer をバックグラウンド投入し future を保持
                        future = self._execute_step(
                            batch[0], steps, user_message,
                            self.executor, on_step,
                            reviewer_pool=reviewer_pool,
                            on_token=on_token,
                            workflow=workflow,
                        )
                        if future is not None:
                            pending = (batch[0], future)
                    else:
                        # 並列実行: join_policy / workflow を渡す
                        self._execute_steps_parallel(
                            batch, steps, user_message, on_step, workflow=workflow
                        )

                # 最後の逐次ステップの Reviewer を処理
                if pending is not None and not workflow_aborted:
                    prev_step, prev_future = pending
                    try:
                        ok, reason = prev_future.result()
                        if not ok and reason:
                            safe_print(C.yellow(
                                f"  ↻ Reviewer(Step {prev_step.index}): {reason[:80]}"
                            ), flush=True)
                            action, _ = workflow.resolve_failure(prev_step)
                            if action == "skip":
                                prev_step.status = "skipped"
                                if on_step:
                                    on_step(prev_step)
                            elif action != "abort":
                                correction_result = self.executor.run_stream(
                                    f"[Reviewer からの修正指示]\n{reason}\n\n"
                                    f"[全体タスク] {user_message}\n"
                                    f"[修正対象ステップ] {prev_step.description}\n"
                                    f"問題を修正してください。",
                                    callback=on_token,
                                )
                                if workflow:
                                    workflow.parse_state_updates(correction_result)
                                steps.append(PlanStep(
                                    index=len(steps) + 1,
                                    description=f"[Reviewer修正] Step {prev_step.index}",
                                    status="done",
                                    result=correction_result,
                                ))
                        else:
                            # 成功時の on_success チェック（最終ステップ）
                            s_action, s_jump = workflow.resolve_success(prev_step)
                            if s_action == "abort":
                                workflow_aborted = True
                            elif s_action == "goto" and s_jump is not None:
                                safe_print(C.orange(
                                    f"  ↷  Step {prev_step.index} 成功 → Step {s_jump} へジャンプ"
                                ), flush=True)
                                _do_goto(s_jump)
                    except Exception as e:
                        log.warning({"event": "reviewer_last_error", "error": str(e)})

            if workflow.state:
                safe_print(C.gray(
                    f"  [WorkflowGraph] 最終ステート: {json.dumps(workflow.state, ensure_ascii=False)}"
                ), flush=True)
            log.info({"event": "workflow_complete", "summary": workflow.summary(),
                      "final_state": workflow.state})

            for step in steps:
                results.append(f"[Step {step.index}] {step.description}\n{step.result}")

            self.executor.end_task()

            # ── 5. 最終まとめ ───────────────────────────────────────────
            summary_prompt = (
                f"以下のタスクが完了しました。結果を簡潔にまとめてください。\n\n"
                f"タスク: {user_message}\n\n"
                + "\n\n".join(results)
            )
            final_result = self.executor.run_stream(summary_prompt, callback=on_token)

            # ── 6. Reflection Loop ──
            safe_print(C.gray("\n  [Reflection: 最終結果を検証中...]"), flush=True)
            final_result, helpful, unhelpful = self._reflect_and_correct(
                user_message, final_result, steps, 
                injected_lessons=injected_lesson_texts, on_token=on_token
            )

            # ── 7. フィードバック適用 & 新規教訓抽出 ──
            if self.long_term_memory:
                # 注入された教訓の評価を反映
                for l_text in helpful:
                    self.long_term_memory.update_lesson_feedback(l_text, is_helpful=True)
                for l_text in unhelpful:
                    self.long_term_memory.update_lesson_feedback(l_text, is_helpful=False)

                # 新規教訓の抽出
                try:
                    _api_key = self.rotator.pick()[0].api_key
                    prev_thinking = self.reflector.thinking_enabled
                    self.reflector.thinking_enabled = False
                    lesson_raw = self.reflector.run(
                        f"[タスク]\n{user_message[:500]}\n\n"
                        f"[最終結果の要約]\n{final_result[:1000]}\n\n"
                        "このタスクと結果から、今後の同種タスクで役立つ技術的な教訓や"
                        "エラー回避の事実を1つだけ簡潔に抽出してください。"
                        "教訓がない場合は「なし」とだけ出力してください。"
                    )
                    self.reflector.thinking_enabled = prev_thinking
                    lesson_text = lesson_raw.strip()
                    if lesson_text and lesson_text not in ("なし", "なし。"):
                        self.long_term_memory.add_lesson(user_message, lesson_text, _api_key)
                        preview = lesson_text[:80] + ("..." if len(lesson_text) > 80 else "")
                        safe_print(C.bold_mem(f"  💡 新しい教訓を記憶しました"), flush=True)
                        safe_print(C.mem(f"     {preview}"), flush=True)
                except Exception as _e:
                    log.warning({"event": "lesson_extract_error", "error": str(_e)})
                    safe_print(C.yellow(f"  ⚠ 教訓の抽出に失敗しました: {_e}"), flush=True)

            return final_result

class InteractiveOrchestrator:
    """
    ReAct（Reason + Act）ベースの対話型オーケストレーター。

    フロー:
      1. Auto-Git バックアップ
      2. AI が Thought をストリーミング出力（中間ターンのみ端末表示）
      3. Tool call (Action) を実行 → 結果 (Observation) を AI に戻す
      4. エラーが MAX_AUTO_RETRY 回続いたらユーザー介入を求める
      5. 書き込み系ツール成功後に Auto-Git チェックポイント
      6. ツールなし応答 = 最終回答を返す（Markdown レンダリングして表示）
    """

    MAX_AUTO_RETRY  = 2   # エラー自動リトライ上限（超えたらユーザー介入）
    MAX_REACT_STEPS = 60  # ReActループ上限

    def __init__(self, agent: "GeminiAgent", auto_git: "AutoGit",
                 long_term_memory: Optional["LongTermMemory"] = None):
        self.agent            = agent
        self.auto_git         = auto_git
        self.react_log        = ReactLog()
        self.long_term_memory = long_term_memory

    @staticmethod
    def _fmt_args(args: dict) -> str:
        return ", ".join(f"{k}={repr(v)[:40]}" for k, v in args.items())

    @staticmethod
    def _extract_thought(text: str) -> str:
        """テキストから Thought: 以降を抽出する。なければ全文を返す。"""
        if not text:
            return ""
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("Thought:"):
                return stripped[len("Thought:"):].strip()
        return text.strip()

    def _execute_with_intervention(
        self, fn_name: str, fn_args: dict, error_counts: dict
    ) -> str:
        """
        ツールを実行する。エラー発生時はAIに内容を返して自律的に解決させる（介入なし）。
        読み取り系ツールはキャッシュを利用する。
        """
        # ── キャッシュヒット確認（読み取り系のみ）────────────────
        if fn_name in _CACHEABLE_TOOLS:
            cache_key = self.agent._make_cache_key(fn_name, fn_args)
            if cache_key in self.agent._tool_cache:
                cached = self.agent._tool_cache[cache_key]
                safe_print(C.gray(f"    [キャッシュ] {len(cached)}文字 (再取得スキップ)"), flush=True)
                return cached

        # ── 自動実行（diff表示のみ） ──────────────────────────
        if fn_name in ("write_file", "edit_file", "patch_file"):
            _print_write_diff(fn_name, fn_args)

        try:
            result = self.agent.tools.execute(fn_name, fn_args)
            error_counts[fn_name] = 0
            result_str = cache_tool_output(fn_name, str(result))
            # キャッシュ登録 / 書き込み後の無効化
            if fn_name in _CACHEABLE_TOOLS:
                self.agent._tool_cache[cache_key] = result_str  # type: ignore[possibly-undefined]
            elif fn_name in ("write_file", "edit_file", "patch_file"):
                self.agent._invalidate_cache_for_path(fn_args.get("path", ""))
            return result_str
        except Exception as e:
            error_counts[fn_name] = error_counts.get(fn_name, 0) + 1
            err_msg = str(e)
            log.error({"event": "react_tool_error", "tool": fn_name,
                        "error": err_msg, "count": error_counts[fn_name]})
            safe_print(C.red(f"\n  ✗ [{fn_name}] エラー: {err_msg}"), flush=True)
            # エラーテキストをAIに返してAIに対処させる（自律的なリカバリ）
            return f"ツール実行エラー: {fn_name}: {err_msg}"

    def run_react(self, user_message: str, on_done=None) -> str:
        """
        ReActループのメインエントリポイント。

        Thought → Action → Observation を繰り返して最終回答を返す。
        on_done: 最終回答が確定した瞬間に呼ばれるコールバック(text) → str
                 教訓保存より前に呼ばれるので、MCP自動モードで即返しに使える。
        """
        # ── 1. Auto-Git バックアップ ──────────────────────────────
        backup_result = self.auto_git.backup(self.agent.cwd)
        safe_print(C.gray(f"  [AutoGit] {backup_result}"), flush=True)

        # ── 1.5. 長期記憶から関連教訓をRAG注入 ──────────────────
        injected_lesson_texts = []
        _api_message = user_message  # API送信用（教訓注入済み）。user_message本体は汚染しない
        if self.long_term_memory and self.agent.rotator.accounts:
            try:
                _api_key = self.agent.rotator.pick()[0].api_key
                _lessons = self.long_term_memory.retrieve_relevant_lessons(
                    user_message, _api_key
                )
                if _lessons:
                    safe_print(C.bold_mem(
                        f"  🧠 記憶から {len(_lessons)} 件をロードしました"
                    ), flush=True)
                    lessons_block, _ = _format_lessons_for_injection(_lessons)
                    _api_message = f"[過去の記憶]\n{lessons_block}\n\n" + user_message
            except Exception as _e:
                log.warning({"event": "rag_retrieve_error", "error": str(_e)})

        # ── 2. メッセージ構築 ─────────────────────────────────────
        self.agent._compact_if_needed()

        ctx    = self.agent._build_context_header()
        task   = self.agent._task_context()
        prefix = "\n\n".join(p for p in [ctx, task] if p)
        aug_message = f"{prefix}\n\n{_api_message}" if prefix else _api_message

        messages: list[dict] = list(self.agent.conversation)
        old_conv_len = len(self.agent.conversation)  # ツール実行履歴保存用
        messages.append({"role": "user", "content": aug_message})

        step_count   = 0
        error_counts: dict[str, int] = {}
        write_tools  = {"write_file", "edit_file", "patch_file", "delete_file"}

        # ── 3. ReActループ ───────────────────────────────────────
        while step_count < self.MAX_REACT_STEPS:
            # PipelineTypewriter でバッファ→レンダリング→タイプライター表示
            _tw = PipelineTypewriter(auto_mode=getattr(self, "_auto_mode", False))
            _tw.start()
            text, tool_calls = self.agent._stream_react_call(
                messages, text_callback=_tw.feed
            )
            _tw.finalize()

            # Ctrl+C 中断
            if text == "__interrupted__":
                return "処理を中断しました。"

            # ── Thought ログ記録 ──────────────────────────────────
            if text:
                thought = self._extract_thought(text)
                if thought:
                    self.react_log.add("thought", content=thought, step=step_count)

            # ── ツールなし = 最終回答 ─────────────────────────────
            if not tool_calls:
                final_text = text or "(応答なし)"
                # ツール実行履歴を含む全ターンを conversation に保存
                self.agent.conversation.append({"role": "user", "content": user_message})
                self.agent.conversation.extend(messages[old_conv_len + 1:])
                self.agent.conversation.append({"role": "assistant", "content": final_text})

                # on_done コールバック: 教訓保存より前に最終回答を通知
                # MCP自動モードではここで即座に回答を返す
                if on_done:
                    try:
                        on_done(final_text)
                    except Exception:
                        pass

                # ── 教訓の自動抽出・保存 ──────────────────────────
                if self.long_term_memory:
                    try:
                        _api_key = self.agent.rotator.pick()[0].api_key
                        # 会話履歴を汚さないよう、一時的に thinking OFF で教訓抽出
                        prev_thinking = self.agent.thinking_enabled
                        self.agent.thinking_enabled = False
                        
                        lesson_raw = self.agent._api_call_with_retry([
                            {"role": "user", "content": (
                                f"[タスク]\n{user_message[:500]}\n\n"
                                f"[最終回答]\n{final_text[:1000]}\n\n"
                                "上記から、将来の同様のタスクでエラーを回避したり効率を上げたりするための「具体的な教訓」を1つだけ抽出してください。\n"
                                "【厳守ルール】\n"
                                "- 解説、導入、箇条書き、思考プロセス、下書きなどは一切含めない。\n"
                                "- 教訓となる「結論の一文」のみを出力すること。\n"
                                "- 教訓がない場合は「なし」とだけ出力すること。"
                            )}
                        ], override_tool_specs=[])
                        
                        self.agent.thinking_enabled = prev_thinking
                        lesson_text = self.agent._extract_text(lesson_raw)
                        
                        if lesson_text and lesson_text.strip() not in ("なし", "なし。", "教訓なし"):
                            self.long_term_memory.add_lesson(user_message, lesson_text.strip(), _api_key)
                            preview = lesson_text.strip()[:80] + ("..." if len(lesson_text.strip()) > 80 else "")
                            safe_print(C.bold_mem(f"  💡 新しい教訓を記憶しました"), flush=True)
                            safe_print(C.mem(f"     {preview}"), flush=True)
                    except Exception as _e:
                        log.warning({"event": "lesson_extract_error_react", "error": str(_e)})
                        safe_print(C.yellow(f"  ⚠ 教訓の抽出に失敗しました: {_e}"), flush=True)

                return final_text

            # ── アシスタント応答をメッセージ履歴に追加（functionCall 正式形式）──
            messages.append({
                "role": "assistant",
                "content": text or "",
                "function_calls": [
                    {"name": tc["name"], "args": tc.get("args", {})}
                    for tc in tool_calls
                ],
            })

            # ── ツール実行（Action → Observation）───────────────
            tool_results: list[dict] = []

            # 書き込み系ツールが含まれる場合は逐次実行（チェックポイント・介入が必要）
            # 読み取り系のみなら並列実行
            has_write_tool = any(tc.get("name", "") in write_tools for tc in tool_calls)

            if len(tool_calls) > 1 and not has_write_tool:
                # ── 並列実行（読み取り系のみ）──────────────────────
                safe_print(C.orange(f"  ⚡ {len(tool_calls)} ツールを並列実行"), flush=True)
                ordered: list[Optional[dict]] = [None] * len(tool_calls)

                def _par_exec(idx_tc: tuple) -> tuple:
                    idx, tc = idx_tc
                    fn_n = tc.get("name", "")
                    fn_a = tc.get("args", {})
                    safe_print(
                        f"\n  {C.bold_green('⚙')} {C.green(fn_n)}"
                        + C.cyan(f"({self._fmt_args(fn_a)})"),
                        flush=True,
                    )
                    self.react_log.add("action", tool=fn_n, args=fn_a, step=step_count)
                    # キャッシュヒット確認
                    if fn_n in _CACHEABLE_TOOLS:
                        ck = self.agent._make_cache_key(fn_n, fn_a)
                        if ck in self.agent._tool_cache:
                            r_str = self.agent._tool_cache[ck]
                            safe_print(C.gray(f"    [キャッシュ] {len(r_str)}文字"), flush=True)
                            self.react_log.add("observation", tool=fn_n, result=r_str[:500], step=step_count)
                            return idx, fn_n, r_str
                    try:
                        r = self.agent.tools.execute(fn_n, fn_a)
                        r_str = cache_tool_output(fn_n, str(r))
                        if fn_n in _CACHEABLE_TOOLS:
                            self.agent._tool_cache[ck] = r_str  # type: ignore[possibly-undefined]
                    except Exception as e:
                        r_str = f"ツール実行エラー: {fn_n}: {e}"
                        log.error({"event": "react_tool_error_par", "tool": fn_n, "error": str(e)})
                        safe_print(C.red(f"\n  ✗ [{fn_n}] 並列実行エラー: {e}"), flush=True)
                        safe_print(C.gray("    （並列実行中のため自動リトライ・介入なし — AIがリカバリします）"), flush=True)
                    obs_preview = r_str[:300].replace("\n", " ")
                    safe_print(C.cyan(f"  👁 {obs_preview}"), flush=True)
                    self.react_log.add("observation", tool=fn_n, result=r_str[:500], step=step_count)
                    return idx, fn_n, r_str

                with ThreadPoolExecutor(max_workers=len(tool_calls)) as tpool:
                    for idx, fn_n, r_str in tpool.map(_par_exec, enumerate(tool_calls)):
                        ordered[idx] = {"tool": fn_n, "result": r_str}
                tool_results = ordered  # type: ignore
            else:
                # ── 逐次実行（書き込み系を含む場合・単一ツール）──────
                for tc in tool_calls:
                    fn_name = tc.get("name", "")
                    fn_args = tc.get("args", {})
                    args_preview = self._fmt_args(fn_args)

                    safe_print(
                        f"\n  {C.bold_green('⚙')} {C.green(fn_name)}"
                        + C.cyan(f"({args_preview})"),
                        flush=True,
                    )
                    self.react_log.add("action", tool=fn_name, args=fn_args, step=step_count)

                    result_str = self._execute_with_intervention(fn_name, fn_args, error_counts)

                    # Auto-checkpoint: 書き込み系ツール成功後に自動コミット
                    # エラー・スキップ・キャンセル時はチェックポイントを行わない
                    _non_success = (
                        "ツール実行エラー: ",
                        "[ユーザーがスキップを選択]",
                        "[ユーザーがキャンセル]",
                        "ユーザーによるキャンセル: ",
                        "[ユーザー指示]",
                    )
                    if fn_name in write_tools and not any(
                        result_str.startswith(p) for p in _non_success
                    ):
                        self.auto_git.checkpoint(
                            self.agent.cwd, fn_name, fn_args.get("path", "")
                        )

                    obs_preview = result_str[:300].replace("\n", " ")
                    safe_print(C.cyan(f"  👁 {obs_preview}"), flush=True)
                    self.react_log.add(
                        "observation", tool=fn_name,
                        result=result_str[:500], step=step_count
                    )
                    tool_results.append({
                        "tool":   fn_name,
                        "result": result_str,
                    })

            # ── Observation を functionResponse 形式でメッセージに追加 ───
            messages.append({
                "role": "user",
                "content": "",
                "function_results": [
                    {"name": r["tool"], "result": r["result"]}
                    for r in tool_results
                ],
            })
            step_count += 1

        # ループ上限到達
        fallback = f"(ReActループ上限 {self.MAX_REACT_STEPS} ステップに達しました)"
        self.agent.conversation.append({"role": "user", "content": user_message})
        self.agent.conversation.extend(messages[old_conv_len + 1:])
        self.agent.conversation.append({"role": "assistant", "content": fallback})
        return fallback

