# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import json
import math
import re
import ast
import os
import time
import threading
import traceback
import collections
import urllib.request
import urllib.error
import urllib.parse
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional, Any
from concurrent.futures import ThreadPoolExecutor
from v4_modules.utils import safe_print, C, log, _try_read_file_text
from v4_modules.config import (AccountConfig, GEMINI_API_BASE,
                                _DEFAULT_MODEL, _EMBEDDING_MODEL, _HYDE_MODEL)

# リランキング用サーキットブレーカー
_rerank_failure_count: int = 0
_rerank_cooldown_until: float = 0.0
_RERANK_COOLDOWN_SEC: float = 60.0   # 429 連続失敗時にスキップする秒数
_RERANK_FAIL_THRESHOLD: int = 3      # 何回連続失敗でクールダウンに入るか

def get_embedding(text: str, api_key: str) -> list:
    """Gemini embedding API でテキストをベクトル化する（標準ライブラリのみ）"""
    url = f"{GEMINI_API_BASE}/{_EMBEDDING_MODEL}:embedContent?key={api_key}"
    payload = json.dumps({
        "content": {"parts": [{"text": text[:30000]}]}
    }).encode("utf-8")

    max_retries = 5
    base_backoff = 10.0  # より保守的なバックオフ
    for attempt in range(max_retries):
        req = urllib.request.Request(
            url, data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read().decode("utf-8"))
                return data.get("embedding", {}).get("values", [])
        except urllib.error.HTTPError as e:
            if e.code == 429 and attempt < max_retries - 1:
                wait_time = base_backoff * (2 ** attempt)
                log.info({"event": "embedding_429_wait", "attempt": attempt + 1, "wait": wait_time})
                time.sleep(wait_time)
                continue
            log.warning({"event": "embedding_error", "error": str(e)})
            break
        except Exception as e:
            log.warning({"event": "embedding_error", "error": str(e)})
            break
    return []

def get_embeddings_batch(texts: list[str], api_key: str) -> list[list]:
    """Gemini batchEmbedContents API で複数のテキストを一括ベクトル化する"""
    if not texts:
        return []
    
    # 制限: 最大 100 件ずつ処理
    BATCH_SIZE = 100
    all_embeddings = []
    
    for i in range(0, len(texts), BATCH_SIZE):
        batch_texts = texts[i:i + BATCH_SIZE]
        url = f"{GEMINI_API_BASE}/{_EMBEDDING_MODEL}:batchEmbedContents?key={api_key}"
        
        requests = []
        for t in batch_texts:
            requests.append({
                "model": f"models/{_EMBEDDING_MODEL}",
                "content": {"parts": [{"text": t[:30000]}]}
            })
            
        payload = json.dumps({"requests": requests}).encode("utf-8")
        
        max_retries = 3
        base_backoff = 5.0
        batch_results = [[] for _ in batch_texts]
        
        for attempt in range(max_retries):
            req = urllib.request.Request(
                url, data=payload,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            try:
                with urllib.request.urlopen(req, timeout=60) as resp:
                    data = json.loads(resp.read().decode("utf-8"))
                    embs = data.get("embeddings", [])
                    batch_results = [e.get("values", []) for e in embs]
                    break
            except urllib.error.HTTPError as e:
                if e.code == 429 and attempt < max_retries - 1:
                    wait_time = base_backoff * (2 ** attempt)
                    log.info({"event": "batch_embedding_429_wait", "attempt": attempt + 1, "wait": wait_time})
                    time.sleep(wait_time)
                    continue
                log.warning({"event": "batch_embedding_error", "error": str(e)})
                break
            except Exception as e:
                log.warning({"event": "batch_embedding_error", "error": str(e)})
                break
        
        all_embeddings.extend(batch_results)
        
    return all_embeddings

def cosine_similarity(v1: list, v2: list) -> float:
    """2つのベクトルのコサイン類似度を計算する（math モジュールのみ使用）"""
    if not v1 or not v2 or len(v1) != len(v2):
        return 0.0
    dot   = sum(a * b for a, b in zip(v1, v2))
    norm1 = math.sqrt(sum(a * a for a in v1))
    norm2 = math.sqrt(sum(b * b for b in v2))
    if norm1 == 0.0 or norm2 == 0.0:
        return 0.0
    return dot / (norm1 * norm2)

def _rag_tokenize(text: str) -> list[str]:
    """日本語・英語対応トークナイザ（全RAGコンポーネント共通）"""
    return re.findall(r'[\w\u3040-\u9fff]+', text.lower())

def _bm25_scores(
    query_tokens: list[str],
    corpus_tokens: list[list[str]],
    k1: float = 1.5,
    b: float = 0.75,
) -> list[float]:
    """
    BM25 スコアを計算して corpus_tokens と同じ長さのリストで返す。
    Robertson et al. の BM25 式を使用（k1=1.5, b=0.75）。
    """
    N = len(corpus_tokens)
    if N == 0:
        return []
    avgdl = sum(len(d) for d in corpus_tokens) / N
    df: dict[str, int] = {}
    for doc in corpus_tokens:
        for w in set(doc):
            df[w] = df.get(w, 0) + 1
    scores = []
    for doc in corpus_tokens:
        score = 0.0
        dl = len(doc)
        tf_map = collections.Counter(doc)
        for term in set(query_tokens):
            if term not in tf_map:
                continue
            tf = tf_map[term]
            idf = math.log((N - df.get(term, 0) + 0.5) / (df.get(term, 0) + 0.5) + 1.0)
            tf_norm = tf * (k1 + 1) / (tf + k1 * (1 - b + b * dl / max(avgdl, 1)))
            score += idf * tf_norm
        scores.append(score)
    return scores

def _rrf_combine(lists: list[list[tuple]], k: int = 60) -> list[tuple]:
    """
    Reciprocal Rank Fusion: 複数の (score, item) ランキングリストを統合する。
    同一アイテムの判定に id() を使用。
    Returns: [(rrf_score, item), ...] 降順ソート済み
    """
    rrf: dict[int, tuple] = {}
    for ranked in lists:
        for rank, (_, item) in enumerate(ranked):
            key = id(item)
            prev_score = rrf[key][0] if key in rrf else 0.0
            rrf[key] = (prev_score + 1.0 / (k + rank + 1), item)
    return sorted(rrf.values(), key=lambda x: x[0], reverse=True)

def _hyde_generate(query: str, api_key: str, timeout: int = 8) -> str:
    """
    HyDE (Hypothetical Document Embeddings):
    クエリに対する仮想的な回答文書を生成して返す。
    生成失敗・タイムアウト時は空文字を返す（呼び出し元は元のクエリにフォールバック）。
    """
    try:
        url = f"{GEMINI_API_BASE}/{_HYDE_MODEL}:generateContent?key={api_key}"
        payload = {
            "contents": [{"role": "user", "parts": [{"text": (
                "次の質問・タスクに対する典型的な回答を100文字以内で生成してください。"
                "正確さより「こういう内容が答えになる」という形式を重視してください。\n\n"
                f"質問: {query}"
            )}]}],
            "generationConfig": {"maxOutputTokens": 150, "temperature": 0.2},
        }
        data = json.dumps(payload).encode()
        req = urllib.request.Request(url, data=data,
                                     headers={"Content-Type": "application/json"},
                                     method="POST")
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            result = json.loads(resp.read())
        text = (result.get("candidates", [{}])[0]
                .get("content", {}).get("parts", [{}])[0].get("text", ""))
        return text.strip()
    except Exception:
        return ""

def _rerank_generate(query: str, documents: list[tuple], api_key: str, timeout: int = 10, rerank_key: Optional[str] = None) -> list[Any]:
    """
    LLMを用いたリランキング。
    documents: [(score, item), ...]
    Returns: [item, ...] 関連度順にソートされたアイテムのリスト
    """
    global _rerank_failure_count, _rerank_cooldown_until

    if not documents:
        return []

    # rerank_key が渡されていればそちらを優先
    _key = rerank_key or api_key

    # サーキットブレーカー: クールダウン中はスキップ
    if time.monotonic() < _rerank_cooldown_until:
        return [item for _, item in documents[:5]]

    candidates = documents[:10]

    def extract_text(item):
        if isinstance(item, str): return item
        if isinstance(item, dict):
            return item.get("lesson") or item.get("content") or item.get("text") or str(item)
        return str(item)

    doc_texts = [extract_text(item) for _, item in candidates]
    formatted_docs = "\n".join([f"[{i}] {text[:500]}" for i, text in enumerate(doc_texts)])
    prompt = (
        f"クエリ: {query}\n\n"
        f"以下のドキュメントを、クエリに対する関連度に基づいて 0 (全く関係ない) から 10 (非常に重要) でスコアリングしてください。\n"
        f"出力は必ず JSON 形式で、スコアのリストのみを返してください。例: [8, 2, 10, 5, ...]\n\n"
        f"{formatted_docs}"
    )

    url = f"{GEMINI_API_BASE}/{_HYDE_MODEL}:generateContent?key={_key}"
    payload = {
        "contents": [{"role": "user", "parts": [{"text": prompt}]}],
        "generationConfig": {"response_mime_type": "application/json", "temperature": 0.0},
    }
    data = json.dumps(payload).encode()

    max_retries = 3
    base_backoff = 4.0
    for attempt in range(max_retries):
        req = urllib.request.Request(url, data=data,
                                     headers={"Content-Type": "application/json"},
                                     method="POST")
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                result = json.loads(resp.read())

            res_text = (result.get("candidates", [{}])[0]
                        .get("content", {}).get("parts", [{}])[0].get("text", "[]"))
            scores = json.loads(res_text)

            if not isinstance(scores, list) or len(scores) != len(candidates):
                return [item for _, item in candidates[:5]]

            reranked = [(float(score), candidates[i][1]) for i, score in enumerate(scores)]
            reranked.sort(key=lambda x: x[0], reverse=True)

            # 成功: 失敗カウントをリセット
            _rerank_failure_count = 0
            return [item for _, item in reranked[:5]]

        except urllib.error.HTTPError as e:
            if e.code == 429 and attempt < max_retries - 1:
                wait_time = base_backoff * (2 ** attempt)
                log.info({"event": "rerank_429_wait", "attempt": attempt + 1, "wait": wait_time})
                time.sleep(wait_time)
                continue
            # 429 で最終リトライ失敗 → 失敗カウントを増やしクールダウン判定
            _rerank_failure_count += 1
            if _rerank_failure_count >= _RERANK_FAIL_THRESHOLD:
                _rerank_cooldown_until = time.monotonic() + _RERANK_COOLDOWN_SEC
                log.warning({"event": "rerank_circuit_open",
                             "cooldown_sec": _RERANK_COOLDOWN_SEC,
                             "fail_count": _rerank_failure_count})
            log.warning({"event": "rerank_error", "error": str(e)})
            break
        except Exception as e:
            log.warning({"event": "rerank_error", "error": str(e)})
            break

    return [item for _, item in candidates[:5]]

_SW_CHUNK_CHARS = 300    # スライディングウィンドウのチャンクサイズ（文字数）

_SW_OVERLAP_CHARS = 100  # オーバーラップ文字数

def _sliding_window_chunks(text: str,
                            size: int = _SW_CHUNK_CHARS,
                            overlap: int = _SW_OVERLAP_CHARS) -> list[str]:
    """
    テキストをスライディングウィンドウでチャンク化する。
    短いテキストはそのまま返す。
    """
    if len(text) <= size:
        return [text] if text.strip() else []
    chunks: list[str] = []
    step = max(size - overlap, 1)
    i = 0
    while i < len(text):
        chunk = text[i:i + size].strip()
        if chunk:
            chunks.append(chunk)
        i += step
    return chunks

_LESSON_TTL_DAYS = 30

_LESSON_MERGE_THRESHOLD = 0.82

def _parse_dt(dt_str: str) -> datetime:
    """ISO形式の日時文字列を datetime に変換する（失敗時は datetime.min）"""
    try:
        return datetime.fromisoformat(dt_str)
    except (ValueError, TypeError):
        return datetime.min

_TAG_PATTERNS: dict[str, str] = {
    "powershell": r"powershell|ps1|\bpwd\b|cmdlet|get-|set-|new-|remove-",
    "file":       r"ファイル|フォルダ|read_file|write_file|edit_file|\.py\b|\.json\b|\.txt\b",
    "web":        r"web|http|url|fetch|検索|wikipedia|ウェブ",
    "python":     r"python|\.py|import |def |class |\bpip\b",
    "git":        r"\bgit\b|commit|branch|merge|push|pull|auto.?git",
    "api":        r"\bapi\b|endpoint|request|response|\bjson\b|curl",
}

def _detect_tags(text: str) -> list:
    """テキストからタスクタイプタグを自動検出してリストで返す (#5)"""
    tl = text.lower()
    return [tag for tag, pat in _TAG_PATTERNS.items() if re.search(pat, tl)]

def _compress_lesson(lesson: str, max_chars: int = 180) -> str:
    """
    教訓テキストをプロンプト注入用に圧縮する (#6)。
    句点/ピリオド/感嘆符で文境界を検出し、最大2文 or max_chars 文字に収める。
    APIコールなし・標準ライブラリのみ。
    """
    if len(lesson) <= max_chars:
        return lesson
    # 文境界パターン: 句点・。！？.!? の直後で分割
    sentences = re.split(r'(?<=[。．！？.!?])\s*', lesson.strip())
    sentences = [s.strip() for s in sentences if s.strip()]
    # 最大2文を結合してみて収まるか確認
    for n in (2, 1):
        candidate = "".join(sentences[:n])
        if candidate and len(candidate) <= max_chars:
            return candidate
    # それでも長い場合は単純にトリム
    return lesson[:max_chars - 1] + "…"

class LongTermMemory:
    """
    lessons_db.json をローカルストレージとして使用する長期記憶クラス。

    強化内容:
      #1 TF-IDF フォールバック — Embedding API 失敗時にキーワード類似度で代替
      #2 Embedding セッションキャッシュ — 同一テキストの API 呼び出しを省略
      #3 use_count ブースト — 実績ある教訓のスコアを自然に底上げ
      #4 重複自動マージ — 類似度 0.92 以上なら追加をスキップして肥大化防止
      #5 タスクタイプタグ — powershell/file/web 等で候補を事前フィルタ
      #7 TTL 自動廃棄 — 30日以上未使用 & use_count==0 の教訓を起動時削除
    """

    def __init__(self, db_path: str = "lessons_db.json"):
        self.db_path    = Path(db_path)
        self._lessons:  list[dict]       = []
        self._emb_cache: dict[str, list] = {}  # #2: セッション内 embedding キャッシュ
        self._load()
        self._expire_old_lessons()             # #7: 起動時に TTL チェック

    # ── I/O ────────────────────────────────────────────────────

    def _load(self):
        if self.db_path.exists():
            try:
                data = json.loads(
                    self.db_path.read_text(encoding="utf-8", errors="replace")
                )
                self._lessons = data if isinstance(data, list) else []
            except Exception:
                self._lessons = []

    def _save(self):
        """
        embedding 配列を1行コンパクト形式で保存し、
        それ以外のフィールドは読みやすく indent=2 で出力する。
        """
        try:
            if not self._lessons:
                self.db_path.write_text("[]", encoding="utf-8")
                return

            parts = []
            for entry in self._lessons:
                emb  = entry.get("embedding", [])
                rest = {k: v for k, v in entry.items() if k != "embedding"}
                
                # rest を indent=2 でシリアライズ
                rest_str = json.dumps(rest, ensure_ascii=False, indent=2)
                # 末尾の '}' を取り除いて embedding を挿入
                rest_str = rest_str.rstrip().rstrip('}')
                emb_str  = json.dumps(emb, separators=(",", ":"), ensure_ascii=False)
                
                merged = f"{rest_str},\n  \"embedding\": {emb_str}\n}}"
                parts.append(merged)
            
            content = "[\n" + ",\n".join(parts) + "\n]"
            self.db_path.write_text(content, encoding="utf-8")
        except Exception as e:
            log.warning({"event": "lessons_db_save_error", "error": str(e)})

    # ── #7: TTL 自動廃棄 ────────────────────────────────────────

    def _expire_old_lessons(self):
        """教訓とセッションの TTL に基づいて期限切れデータを削除する"""
        now = datetime.now()
        before = len(self._lessons)
        
        def is_expired(e):
            e_type = e.get("type", "lesson")
            created_at = _parse_dt(e.get("created_at", ""))
            if e_type == "session":
                ttl = e.get("ttl_days", 14)
                return (now - created_at).days >= ttl
            else:
                # 既存の教訓ロジック: 30日以上未使用 & use_count==0
                cutoff = now - timedelta(days=_LESSON_TTL_DAYS)
                return e.get("use_count", 0) == 0 and created_at < cutoff

        self._lessons = [e for e in self._lessons if not is_expired(e)]
        removed = before - len(self._lessons)
        if removed:
            self._save()
            safe_print(C.mem(f"  🗑  期限切れ記憶 {removed} 件を削除しました"), flush=True)
            log.info({"event": "memory_expired", "removed": removed})

    # ── #2: セッション内 Embedding キャッシュ ──────────────────

    def _get_embedding_cached(self, text: str, api_key: str) -> list:
        """キャッシュ済みなら API を呼ばずに返す"""
        key = text[:200]  # キャッシュキーは先頭200文字で十分
        if key in self._emb_cache:
            return self._emb_cache[key]
        vec = get_embedding(text, api_key)
        if vec:
            self._emb_cache[key] = vec
        return vec

    # ── #4: 重複判定 ────────────────────────────────────────────

    def _is_duplicate(self, new_vec: list) -> bool:
        """既存教訓に類似度 _LESSON_MERGE_THRESHOLD 以上のものがあれば True"""
        for entry in self._lessons:
            emb = entry.get("embedding", [])
            if emb and cosine_similarity(new_vec, emb) >= _LESSON_MERGE_THRESHOLD:
                return True
        return False

    # ── #1: TF-IDF フォールバック検索 ──────────────────────────

    def _tfidf_retrieve(
        self, query: str, candidates: list, threshold: float
    ) -> list:
        """
        Embedding 失敗時のフォールバック。
        collections.Counter + math のみで TF-IDF コサイン類似度を計算する。
        TF-IDF は絶対値がコサイン埋め込みより低いため閾値を半分に緩める。
        """
        import collections

        def _tok(text: str) -> list:
            return re.findall(r'[\w\u3040-\u9fff]+', text.lower())

        # DF 計算（コーパス = 教訓テキスト + タスククエリ）
        corpus_tokens = [
            _tok(e.get("lesson", "") + " " + e.get("task_query", ""))
            for e in candidates
        ]
        df: dict[str, int] = {}
        for doc in corpus_tokens:
            for w in set(doc):
                df[w] = df.get(w, 0) + 1
        N = max(len(corpus_tokens), 1)

        def _tfidf(tokens: list) -> dict:
            tf = collections.Counter(tokens)
            total = max(len(tokens), 1)
            return {
                w: (c / total) * math.log((N + 1) / (df.get(w, 0) + 1))
                for w, c in tf.items()
            }

        def _cos_dict(v1: dict, v2: dict) -> float:
            keys = set(v1) & set(v2)
            if not keys:
                return 0.0
            dot = sum(v1[k] * v2[k] for k in keys)
            n1 = math.sqrt(sum(v * v for v in v1.values()))
            n2 = math.sqrt(sum(v * v for v in v2.values()))
            return dot / (n1 * n2) if n1 and n2 else 0.0

        q_vec = _tfidf(_tok(query))
        soft_threshold = threshold * 0.5  # TF-IDF は閾値を緩める
        scored = []
        for entry, doc_tok in zip(candidates, corpus_tokens):
            d_vec = _tfidf(doc_tok)
            sim   = _cos_dict(q_vec, d_vec)
            boost = 1.0 + math.log1p(entry.get("use_count", 0)) * 0.1  # #3
            if sim * boost >= soft_threshold:
                scored.append((sim * boost, entry))
        return scored

    # ── 公開 API ────────────────────────────────────────────────

    def _clean_lesson_text(self, text: str) -> str:
        """教訓テキストから下書きや思考プロセスなどのゴミを取り除く"""
        # 1. AIが生成した典型的な「下書き/Draft」パターンを削除
        text = re.sub(r'(?i)\*?\s*Draft\s*\d+\s*:?.*?\n', '', text)
        text = re.sub(r'(?i)Selected\s*Point:.*?\n', '', text)
        text = re.sub(r'(?i)Final\s*Selection:.*?\n', '', text)
        # 2. 箇条書き記号の羅列やメタ情報を削除
        text = re.sub(r'\*\s*Task:.*?\n', '', text)
        text = re.sub(r'\*\s*Outcome:.*?\n', '', text)
        text = re.sub(r'\*\s*Reason:.*?\n', '', text)
        # 3. 文末の余計な空白や改行を整理
        lines = [line.strip() for line in text.splitlines() if line.strip()]
        # 4. 複数ある場合は最後の「結論」らしき一文を優先
        if lines:
            # 最後の1行が十分に意味を持つならそれを採用
            last_line = lines[-1]
            if len(last_line) > 10:
                return last_line
        return "\n".join(lines)

    def add_lesson(self, task_query: str, lesson_text: str, api_key: str):
        """タスクと教訓をベクトル化してDBに追記する（類似時はマージ）"""
        # クリーニング実行
        lesson_text = self._clean_lesson_text(lesson_text)
        
        combined  = f"task: retrieval_document: {task_query} {lesson_text}"
        embedding = self._get_embedding_cached(combined, api_key)

        if not embedding:
            log.warning({"event": "lesson_embedding_failed_bm25_only", "task": task_query[:50]})
            safe_print(C.yellow("  ⚠ Embedding 失敗 — 教訓はBM25のみで保存（意味検索不可）"), flush=True)

        # 類似教訓の検索とマージ
        found_idx = -1
        for i, entry in enumerate(self._lessons):
            emb = entry.get("embedding", [])
            if emb and cosine_similarity(embedding, emb) >= _LESSON_MERGE_THRESHOLD:
                found_idx = i
                break
        
        if found_idx >= 0:
            # 既存の教訓を新しい（より洗練された）内容で更新し、カウントを増やす
            old = self._lessons[found_idx]
            old["lesson"] = lesson_text
            old["embedding"] = embedding
            old["use_count"] = old.get("use_count", 0) + 1
            old["last_used_at"] = datetime.now().isoformat(timespec="seconds")
            self._save()
            log.info({"event": "lesson_merged", "lesson_preview": lesson_text[:60]})
            safe_print(C.mem("  💡 既存の知識をアップデートしました"), flush=True)
            return

        tags = _detect_tags(f"{task_query} {lesson_text}")

        entry: dict = {
            "type":        "lesson",
            "task_query":  task_query,
            "lesson":      lesson_text,
            "embedding":   embedding,
            "tags":        tags,
            "use_count":   0,
            "created_at":  datetime.now().isoformat(timespec="seconds"),
            "last_used_at": None,
        }
        self._lessons.append(entry)
        self._save()
        log.info({"event": "lesson_added", "tags": tags, "lesson_preview": lesson_text[:80]})
        if embedding:
            safe_print(C.mem(f"  💾 教訓を保存しました（Embedding済み）"), flush=True)
        else:
            safe_print(C.yellow(f"  💾 教訓を保存しました（BM25のみ・Embedding失敗）"), flush=True)

    def retrieve_relevant_lessons(
        self,
        current_task: str,
        api_key: str,
        top_k: int = 2,
        threshold: float = 0.6,
        rerank_key: Optional[str] = None,
    ) -> list:
        """
        現在タスクに類似した教訓を閾値以上のものから最大 top_k 件返す。

        検索フロー:
          1. #5 タグで候補を事前フィルタ（タグ一致なければ全件）
          2. #2 キャッシュ付き Embedding でクエリをベクトル化
          3. Embedding 成功 → コサイン類似度 + #3 use_count ブースト
             Embedding 失敗 → #1 TF-IDF フォールバック
          4. #3 使用回数・最終使用日時を更新して保存
        """
        if not self._lessons:
            return []

        # #5: タグ事前フィルタリング
        query_tags = set(_detect_tags(current_task))
        if query_tags:
            candidates = [
                e for e in self._lessons
                if not e.get("tags") or (query_tags & set(e.get("tags", [])))
            ]
            if not candidates:
                candidates = self._lessons  # タグ不一致なら全件フォールバック
        else:
            candidates = self._lessons

        # ── C: HyDE でクエリを拡張（候補10件以上の場合のみ）────────
        # 小規模コーパスでは BM25+Embedding で十分。HyDE はAPI消費が大きいためスキップ。
        if len(candidates) >= 10:
            hyde_text = _hyde_generate(current_task, api_key)
            if hyde_text:
                log.info({"event": "rag_hyde_applied", "preview": hyde_text[:60]})
        else:
            hyde_text = ""
        search_query = (
            f"task: retrieval_query: {current_task} {hyde_text}".strip()
            if hyde_text else f"task: retrieval_query: {current_task}"
        )

        # ── B: BM25 スコアを計算 ─────────────────────────────────
        q_tokens = _rag_tokenize(current_task)
        corpus_tokens = [
            _rag_tokenize(e.get("lesson", "") + " " + e.get("task_query", ""))
            for e in candidates
        ]
        bm25_raw = _bm25_scores(q_tokens, corpus_tokens)
        bm25_ranked: list[tuple] = sorted(
            [
                (s * (1.0 + math.log1p(e.get("use_count", 0)) * 0.1), e)
                for s, e in zip(bm25_raw, candidates) if s > 0
            ],
            key=lambda x: x[0], reverse=True,
        )

        # ── #2: キャッシュ付き Embedding ────────────────────────
        query_vec = self._get_embedding_cached(search_query, api_key)
        emb_ranked: list[tuple] = []
        if query_vec:
            for entry in candidates:
                emb = entry.get("embedding", [])
                if not emb:
                    continue
                sim = cosine_similarity(query_vec, emb)
                use_boost = 1.0 + math.log1p(entry.get("use_count", 0)) * 0.1
                fail_penalty = entry.get("fail_count", 0) * 0.15
                score = (sim * use_boost) - fail_penalty
                if score > 0:
                    emb_ranked.append((score, entry))
            emb_ranked.sort(key=lambda x: x[0], reverse=True)
        else:
            log.info({"event": "rag_embedding_unavailable_lesson"})

        # ── B: RRF で Embedding + BM25 を統合 ────────────────────
        active_lists = [lst for lst in [emb_ranked, bm25_ranked] if lst]
        if not active_lists:
            return []
        combined = _rrf_combine(active_lists)
        # Rerank は候補5件以上の場合のみ（少数ではAPI消費に見合わない）
        if len(combined) >= 5:
            reranked = _rerank_generate(current_task, combined, api_key, rerank_key=rerank_key)
        else:
            reranked = [item for _, item in combined]
        return reranked[:top_k]

    def update_lesson_feedback(self, lesson_text: str, is_helpful: bool):
        """
        教訓の評価を更新する (#1 ネガティブフィードバック)。
        helpful なら use_count を増やし, unhelpful なら fail_count を増やす。
        fail_count が累積 3 回を超え, かつ使用回数より多い場合は削除。
        """
        for entry in self._lessons:
            if entry.get("lesson") == lesson_text:
                if is_helpful:
                    entry["use_count"] = entry.get("use_count", 0) + 1
                    entry["last_used_at"] = datetime.now().isoformat(timespec="seconds")
                else:
                    entry["fail_count"] = entry.get("fail_count", 0) + 1
                    log.info({"event": "lesson_penalized", "lesson": lesson_text[:60]})

                fails = entry.get("fail_count", 0)
                uses  = entry.get("use_count", 0)
                if fails >= 3 and fails > uses:
                    self._lessons.remove(entry)
                    log.info({"event": "lesson_purged", "lesson": lesson_text[:60]})
                    safe_print(C.mem(f"  🗑  役に立たないと判定された教訓を削除しました"), flush=True)

                self._save()
                break



class SessionRAG:
    """
    会話履歴をチャンク化してベクトル検索可能にするセッション内RAG。

    _compact_if_needed() がトリガーされた際に圧縮対象のメッセージをAI要約の代わりに
    このストアへアーカイブし、次ターン以降で関連部分だけを自動検索して注入する。
    永続化不要（セッション終了で破棄）。
    """

    RETRIEVE_TOP_K = 3
    RETRIEVE_THRESHOLD = 0.45
    _TFIDF_THRESHOLD_FACTOR = 0.5

    def __init__(self):
        self._chunks: list[dict] = []  # {text, embedding, label}
        self._emb_cache: dict[str, list] = {}

    def _get_embedding_cached(self, text: str, api_key: str) -> list:
        key = text[:200]
        if key in self._emb_cache:
            return self._emb_cache[key]
        vec = get_embedding(text, api_key)
        if vec:
            self._emb_cache[key] = vec
        return vec

    def store_messages(self, messages: list[dict], api_key: str):
        """
        メッセージリストをスライディングウィンドウでチャンク化してRAGストアに追加する。
        （D: 長いツール結果も細かく分割されるため検索精度が向上する）
        """
        for m in messages:
            text = _fmt_msg_for_summary(m)
            if not text.strip():
                continue
            role = m.get("role", "?")
            if m.get("function_results"):
                names = ", ".join(r["name"] for r in m["function_results"])
                label = f"[ツール結果: {names}]"
            elif m.get("function_calls"):
                names = ", ".join(fc["name"] for fc in m["function_calls"])
                label = f"[ツール呼び出し: {names}]"
            else:
                label = f"[{role}]"
            # D: スライディングウィンドウでチャンク化
            for sub_text in _sliding_window_chunks(text):
                emb = self._get_embedding_cached(sub_text, api_key)
                self._chunks.append({"text": sub_text, "embedding": emb, "label": label})

    def retrieve(self, query: str, api_key: str,
                 top_k: int = RETRIEVE_TOP_K,
                 threshold: float = RETRIEVE_THRESHOLD,
                 rerank_key: Optional[str] = None) -> list[dict]:
        """
        ハイブリッド検索（B: BM25 + Embedding + RRF）＋ クエリ拡張（C: HyDE）で
        関連チャンクを最大 top_k 件返す。
        """
        if not self._chunks:
            return []

        # C: HyDE でクエリを拡張（チャンク10件以上の場合のみ）
        if len(self._chunks) >= 10:
            hyde_text = _hyde_generate(query, api_key)
        else:
            hyde_text = ""
        search_query = f"{query} {hyde_text}".strip() if hyde_text else query

        # B: BM25
        q_tokens = _rag_tokenize(search_query)
        corpus_tokens = [_rag_tokenize(c["text"]) for c in self._chunks]
        bm25_raw = _bm25_scores(q_tokens, corpus_tokens)
        bm25_ranked: list[tuple] = sorted(
            [(s, c) for s, c in zip(bm25_raw, self._chunks) if s > 0],
            key=lambda x: x[0], reverse=True,
        )

        # B: Embedding
        query_vec = self._get_embedding_cached(
            f"task: retrieval_query: {search_query}", api_key
        )
        emb_ranked: list[tuple] = []
        if query_vec:
            for chunk in self._chunks:
                emb = chunk.get("embedding")
                if not emb:
                    continue
                sim = cosine_similarity(query_vec, emb)
                if sim >= threshold:
                    emb_ranked.append((sim, chunk))
            emb_ranked.sort(key=lambda x: x[0], reverse=True)
        else:
            log.info({"event": "session_rag_embedding_unavailable"})

        # B: RRF 統合
        active = [lst for lst in [emb_ranked, bm25_ranked] if lst]
        if not active:
            return []
        combined = _rrf_combine(active)
        # Rerank は候補5件以上の場合のみ
        if len(combined) >= 5:
            reranked = _rerank_generate(query, combined, api_key, rerank_key=rerank_key)
        else:
            reranked = [item for _, item in combined]
        return reranked[:top_k]

    def format_context(self, chunks: list[dict]) -> str:
        """検索結果を会話注入用のテキストブロックにフォーマットする。"""
        if not chunks:
            return ""
        lines = [f"  {c['label']}: {c['text']}" for c in chunks]
        return "[セッション記憶から関連情報を検索]\n" + "\n".join(lines)

    @property
    def chunk_count(self) -> int:
        return len(self._chunks)

class ProjectRAG:
    """
    作業フォルダ内のファイルをチャンク化してベクトル検索するRAG。（A）

    チャンク戦略:
      - Python (.py): AST解析で関数/クラス単位にチャンク化 + シンボルマップ作成
      - その他テキスト: CHUNK_LINES 行単位でスライディングウィンドウ

    更新: write_file / edit_file / patch_file 実行後に差分更新される。
    検索: BM25 + Embedding + RRF + HyDE の完全ハイブリッド。
    """

    CHUNK_LINES   = 80      # 非Pythonファイルのチャンクサイズ（行数）
    OVERLAP_LINES = 20      # オーバーラップ行数
    MAX_FILE_BYTES = 120_000
    RETRIEVE_TOP_K = 4
    RETRIEVE_THRESHOLD = 0.35
    _TEXT_EXTS = {
        ".py", ".js", ".ts", ".jsx", ".tsx", ".md", ".txt", ".json",
        ".yaml", ".yml", ".toml", ".ini", ".cfg", ".sh", ".bat", ".ps1",
        ".html", ".css", ".go", ".rs", ".java", ".c", ".cpp", ".h",
    }
    _IGNORE_DIRS = {
        ".git", "__pycache__", "venv", ".venv", "node_modules",
        ".idea", ".vscode", "dist", "build", ".mypy_cache",
    }

    def __init__(self):
        self._chunks: list[dict] = []       # {text, embedding, path, start_line, label}
        self._emb_cache: dict[str, list] = {}
        self._indexed_paths: set[str] = set()
        self._repo_map: dict[str, list[str]] = {}  # path -> [symbols...]
        self._lock = threading.Lock()
        self._is_indexing = False

    def to_dict(self) -> dict:
        """状態をシリアライズ可能な辞書に変換"""
        with self._lock:
            return {
                "chunks": self._chunks,
                "indexed_paths": list(self._indexed_paths),
                "repo_map": self._repo_map,
            }

    def from_dict(self, data: dict):
        """シリアライズされたデータから状態を復元"""
        with self._lock:
            self._chunks = data.get("chunks", [])
            self._indexed_paths = set(data.get("indexed_paths", []))
            self._repo_map = data.get("repo_map", {})

    def save(self, root: str | Path):
        """インデックスをファイルに保存"""
        try:
            cache_path = Path(root) / ".unimog_rag_cache.json"
            data = self.to_dict()
            cache_path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
        except Exception as e:
            log.warning({"event": "project_rag_save_error", "error": str(e)})

    def load(self, root: str | Path) -> bool:
        """インデックスをファイルからロード。成功したら True"""
        try:
            cache_path = Path(root) / ".unimog_rag_cache.json"
            if cache_path.exists():
                data = json.loads(cache_path.read_text(encoding="utf-8"))
                self.from_dict(data)
                return True
        except Exception as e:
            log.warning({"event": "project_rag_load_error", "error": str(e)})
        return False

    def _get_embedding_cached(self, text: str, api_key: str) -> list:
        key = text[:200]
        if key in self._emb_cache:
            return self._emb_cache[key]
        vec = get_embedding(text, api_key)
        if vec:
            self._emb_cache[key] = vec
        return vec

    def _extract_symbols(self, content: str) -> list[str]:
        """ASTを使用してクラス名や関数名を抽出する"""
        symbols = []
        try:
            tree = ast.parse(content)
            for node in ast.walk(tree):
                if isinstance(node, ast.ClassDef):
                    symbols.append(f"class:{node.name}")
                elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    symbols.append(f"def:{node.name}")
        except Exception:
            pass
        return symbols

    def _chunk_python(self, path: Path, content: str) -> list[dict]:
        """AST解析でPythonファイルを関数/クラス単位にチャンク化"""
        lines = content.splitlines()
        chunks: list[dict] = []
        try:
            tree = ast.parse(content)
            for node in ast.walk(tree):
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                    continue
                start = node.lineno - 1
                end = getattr(node, "end_lineno", start + 30)
                text = "\n".join(lines[start:end])
                if len(text.strip()) < 20:
                    continue
                kind = type(node).__name__.replace("FunctionDef", "def").replace("ClassDef", "class")
                label = f"[{path.name}:{node.lineno}] {kind} {node.name}"
                chunks.append({"text": text, "embedding": [],
                               "path": str(path), "start_line": start + 1, "label": label})
        except Exception:
            chunks = self._chunk_by_lines(path, content)
        return chunks

    def _chunk_by_lines(self, path: Path, content: str) -> list[dict]:
        """行単位スライディングウィンドウでチャンク化"""
        lines = content.splitlines()
        chunks: list[dict] = []
        step = max(self.CHUNK_LINES - self.OVERLAP_LINES, 1)
        for i in range(0, len(lines), step):
            chunk_lines = lines[i:i + self.CHUNK_LINES]
            text = "\n".join(chunk_lines).strip()
            if not text:
                continue
            end = min(i + self.CHUNK_LINES, len(lines))
            label = f"[{path.name}:{i+1}-{end}]"
            chunks.append({"text": text, "embedding": [],
                           "path": str(path), "start_line": i + 1, "label": label})
        return chunks

    def index_file(self, path: Path, api_key: str) -> int:
        """1ファイルをインデックスに追加。返値: 追加チャンク数"""
        if not path.is_file() or path.suffix not in self._TEXT_EXTS:
            return 0
        try:
            if path.stat().st_size > self.MAX_FILE_BYTES:
                return 0
            content = _try_read_file_text(path)
        except Exception:
            return 0
            
        with self._lock:
            # 差分更新: 既存エントリを削除
            self._chunks = [c for c in self._chunks if c["path"] != str(path)]
            
            # シンボル抽出 (Repo Map)
            if path.suffix == ".py":
                self._repo_map[str(path)] = self._extract_symbols(content)
                new_chunks = self._chunk_python(path, content)
            else:
                new_chunks = self._chunk_by_lines(path, content)
                
            if not new_chunks:
                return 0
                
            # バッチ Embedding 実行
            texts_to_embed = [c["text"] for c in new_chunks]
            embeddings = get_embeddings_batch(texts_to_embed, api_key)
            
            for chunk, emb in zip(new_chunks, embeddings):
                chunk["embedding"] = emb
                
            self._chunks.extend(new_chunks)
            self._indexed_paths.add(str(path))
            return len(new_chunks)

    def index_directory(self, root: "str | Path", api_key: str) -> int:
        """ディレクトリを再帰的にインデックス化。返値: 追加チャンク総数"""
        with self._lock:
            if self._is_indexing:
                return 0
            self._is_indexing = True
            
        try:
            root = Path(root)
            total = 0
            files_to_index = []
            for path in root.rglob("*"):
                if any(part in self._IGNORE_DIRS for part in path.parts):
                    continue
                if path.is_file() and path.suffix in self._TEXT_EXTS:
                    if str(path) not in self._indexed_paths:
                        files_to_index.append(path)
            
            # 各ファイルを個別にインデックス化（index_file 内でバッチ処理される）
            for f in files_to_index:
                total += self.index_file(f, api_key)
            return total
        finally:
            with self._lock:
                self._is_indexing = False

    def update_file(self, path_str: str, api_key: str) -> None:
        """ファイル変更時の差分更新（write_file / edit_file フック）"""
        path = Path(path_str)
        if path.exists():
            self.index_file(path, api_key)
        else:
            with self._lock:
                self._chunks = [c for c in self._chunks if c["path"] != path_str]
                self._indexed_paths.discard(path_str)
                self._repo_map.pop(path_str, None)

    def retrieve(self, query: str, api_key: str,
                 top_k: int = RETRIEVE_TOP_K,
                 threshold: float = RETRIEVE_THRESHOLD,
                 rerank_key: Optional[str] = None) -> list[dict]:
        """BM25 + Embedding + RRF + HyDE のフルハイブリッド検索"""
        if not self._chunks:
            return []

        # C: HyDE
        hyde_text = _hyde_generate(query, api_key)
        search_query = f"{query} {hyde_text}".strip() if hyde_text else query

        # B: BM25
        q_tokens = _rag_tokenize(search_query)
        corpus_tokens = [_rag_tokenize(c["text"]) for c in self._chunks]
        bm25_raw = _bm25_scores(q_tokens, corpus_tokens)
        bm25_ranked: list[tuple] = sorted(
            [(s, c) for s, c in zip(bm25_raw, self._chunks) if s > 0],
            key=lambda x: x[0], reverse=True,
        )

        # B: Embedding
        query_vec = self._get_embedding_cached(
            f"task: retrieval_query: {search_query}", api_key
        )
        emb_ranked: list[tuple] = []
        if query_vec:
            for chunk in self._chunks:
                emb = chunk.get("embedding")
                if emb:
                    sim = cosine_similarity(query_vec, emb)
                    if sim > 0:
                        emb_ranked.append((sim, chunk))
            emb_ranked.sort(key=lambda x: x[0], reverse=True)

        # B: RRF 統合
        active = [lst for lst in [emb_ranked, bm25_ranked] if lst]
        if not active:
            return []
        combined = _rrf_combine(active)
        reranked = _rerank_generate(query, combined, api_key, rerank_key=rerank_key)
        return reranked[:top_k]

    def format_context(self, chunks: list[dict]) -> str:
        if not chunks:
            return ""
        lines = [f"  {c['label']}:\n{c['text'][:400]}" for c in chunks]
        
        # Repo Map の情報を付与
        repo_info = ""
        if self._repo_map:
            repo_info = "\n[Repo Map - Important Symbols]\n"
            for p, syms in list(self._repo_map.items())[:10]: # 代表的なものをいくつか
                if syms:
                    repo_info += f"  {Path(p).name}: {', '.join(syms[:5])}\n"
        
        return "[コードベース検索結果]\n" + "\n---\n".join(lines) + repo_info

    @property
    def chunk_count(self) -> int:
        return len(self._chunks)

def _fmt_msg_for_summary(m: dict) -> str:
    """要約用にメッセージを1行テキストに変換する"""
    role = m.get("role", "?")
    if m.get("function_results"):
        results = "; ".join(
            f"{r['name']}: {str(r.get('result',''))[:200]}"
            for r in m["function_results"]
        )
        return f"[{role}/tool_result]: {results}"
    if m.get("function_calls"):
        calls = ", ".join(fc["name"] for fc in m["function_calls"])
        return f"[{role}]: {str(m.get('content',''))[:200]} [calls: {calls}]"
    return f"[{role}]: {str(m.get('content', ''))[:500]}"

