# Auto-generated by split_v4.py — do not edit manually
# Original: V4.py
from __future__ import annotations

import threading
import time
import collections
import sys
import os
import re
import logging
import json
import traceback
import math
from pathlib import Path
from typing import Optional, Any
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone


_print_lock = threading.Lock()

def safe_print(*args, **kwargs):
    """複数スレッドからの出力が混ざらないようロック制御する print"""
    with _print_lock:
        print(*args, **kwargs)

def _try_read_file_text(path: Path) -> str:
    """UTF-8で読み込みを試行し、失敗した場合は置換して強制的に読み込む。"""
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")

class C:
    """Matrix Green Theme (All colors unified to Green system)"""
    RESET   = "\033[0m"
    BOLD    = "\033[1m"
    DIM     = "\033[2m"
    # --- ネオンカラー定義 (Green系統) ---
    _RG     = "\033[38;2;0;255;0m"      # Razer Green (メイン)
    _RG_DIM = "\033[38;2;0;64;0m"       # Dark Forest (枠線)
    _WHITE  = "\033[38;2;220;255;220m"  # Mint White (重要テキスト)
    _GRAY   = "\033[38;2;80;120;80m"    # Moss Gray (ログ)
    _PURPLE = "\033[38;2;160;255;120m"  # Pale Lime (AIの思考)
    _CYAN   = "\033[38;2;0;255;180m"    # Seafoam Green (観察・ツール結果)
    _RED    = "\033[38;2;200;255;0m"    # Toxic Yellow (エラー)
    _YELLOW = "\033[38;2;140;255;0m"    # Chartreuse (警告・待機)
    _ORANGE = "\033[38;2;0;200;100m"    # Emerald (並列処理)
    _MEM    = "\033[38;2;0;230;255m"    # Electric Aqua (長期記憶・RAG)
    @staticmethod
    def green(s):      return f"{C._RG}{s}{C.RESET}"
    @staticmethod
    def green_dim(s):  return f"{C._RG_DIM}{s}{C.RESET}"
    @staticmethod
    def white(s):      return f"{C._WHITE}{s}{C.RESET}"
    @staticmethod
    def gray(s):       return f"{C._GRAY}{s}{C.RESET}"
    @staticmethod
    def red(s):        return f"{C._RED}{s}{C.RESET}"
    @staticmethod
    def yellow(s):     return f"{C._YELLOW}{s}{C.RESET}"
    @staticmethod
    def cyan(s):       return f"{C._CYAN}{s}{C.RESET}"
    @staticmethod
    def purple(s):     return f"{C._PURPLE}{s}{C.RESET}"
    @staticmethod
    def orange(s):     return f"{C._ORANGE}{s}{C.RESET}"
    @staticmethod
    def mem(s):        return f"{C._MEM}{s}{C.RESET}"
    @staticmethod
    def bold_mem(s):   return f"{C.BOLD}{C._MEM}{s}{C.RESET}"
    @staticmethod
    def dim(s):        return f"{C.DIM}{s}{C.RESET}"
    @staticmethod
    def bold(s):       return f"{C.BOLD}{s}{C.RESET}"
    @staticmethod
    def bold_green(s): return f"{C.BOLD}{C._RG}{s}{C.RESET}"
    @staticmethod
    def bold_cyan(s):  return f"{C.BOLD}{C._CYAN}{s}{C.RESET}"
    @staticmethod
    def bold_purple(s):return f"{C.BOLD}{C._PURPLE}{s}{C.RESET}"

def render_markdown(text: str) -> str:
    """
    Markdown テキストを ANSI エスケープコードに変換する。
    対応: 見出し / 太字 / 斜体 / インラインコード / コードブロック /
          箇条書き / 番号リスト / 水平線
    """
    lines = text.split("\n")
    out = []
    in_code_block = False
    code_lang = ""

    for line in lines:
        # ── コードブロック ─────────────────────────────
        if line.startswith("```"):
            if not in_code_block:
                in_code_block = True
                code_lang = line[3:].strip()
                label = f" {code_lang}" if code_lang else ""
                out.append(C.green_dim(f"┌─code{label}"))
            else:
                in_code_block = False
                out.append(C.green_dim("└─"))
            continue

        if in_code_block:
            out.append(f"  {C._RG_DIM}{line}{C.RESET}")
            continue

        # ── 水平線 ─────────────────────────────────────
        if re.match(r"^[-*_]{3,}$", line.strip()):
            out.append(C.green_dim("─" * 40))
            continue

        # ── 見出し ─────────────────────────────────────
        m = re.match(r"^(#{1,4})\s+(.*)", line)
        if m:
            level = len(m.group(1))
            title = _render_inline(m.group(2))
            if level == 1:
                out.append(C.bold_green(f"\n{title}"))
                out.append(C.green("─" * min(len(title) + 2, 50)))
            elif level == 2:
                out.append(C.bold_green(f"\n{title}"))
            elif level == 3:
                out.append(C.green(f"{title}"))
            else:
                out.append(C.gray(f"{title}"))
            continue

        # ── 箇条書き ────────────────────────────────────
        m = re.match(r"^(\s*)[-*+]\s+(.*)", line)
        if m:
            indent = len(m.group(1)) // 2
            bullet = ["•", "◦", "▸"][min(indent, 2)]
            out.append(f"{'  ' * indent}  {C.green(bullet)} {_render_inline(m.group(2))}")
            continue

        # ── 番号リスト ──────────────────────────────────
        m = re.match(r"^(\s*)(\d+)\.\s+(.*)", line)
        if m:
            indent = len(m.group(1)) // 2
            num = m.group(2)
            out.append(f"{'  ' * indent}  {C.green(num + '.')} {_render_inline(m.group(3))}")
            continue

        # ── 通常行 ──────────────────────────────────────
        out.append(_render_inline(line))

    return "\n".join(out)

def _render_inline(text: str) -> str:
    """インライン要素を変換する（Green / White / Cyan 限定版）"""
    # インラインコード `code` -> Razer Green
    text = re.sub(r"`([^`]+)`",
                  lambda m: f"{C._RG}{m.group(1)}{C.RESET}", text)
    
    # 太字 **text** -> 白の太字 (最も見やすい)
    text = re.sub(r"\*\*(.+?)\*\*|__(.+?)__",
                  lambda m: f"{C.BOLD}{C._WHITE}{m.group(1) or m.group(2)}{C.RESET}", text)
    
    # 斜体 *text* -> シアンの暗め表示
    text = re.sub(r"\*(.+?)\*|_(.+?)_",
                  lambda m: f"{C._PURPLE}{C.DIM}{m.group(1) or m.group(2)}{C.RESET}", text)
    return text

def print_ascii_art():
    # 上から下へ green → teal → electric aqua のグラデーション
    _G = [
        "\033[38;2;0;255;0m",    # row1: Razer Green
        "\033[38;2;0;255;80m",   # row2: Green-Teal
        "\033[38;2;0;255;160m",  # row3: Teal
        "\033[38;2;160;255;120m",# row4: Pale Lime
        "\033[38;2;0;255;180m",  # row5: Seafoam
        "\033[38;2;0;242;218m",  # row6: Cyan-Green
        "\033[38;2;0;230;255m",  # row7: Electric Aqua
        "\033[38;2;80;220;255m", # row8: Sky Aqua
    ]
    R = C.RESET
    SEP = f"\033[38;2;0;80;80m ──────────────────────────────────────────────────────────────────────────────────\033[0m"
    art = f"""
{_G[0]}   888     888 888b    888 8888888 888b     d888  .d88888b.   .d8888b.      d8888{R}
{_G[1]}   888     888 8888b   888   888   8888b   d8888 d88P" "Y88b d88P  Y88b    d8P888{R}
{_G[2]}   888     888 88888b  888   888   88888b.d88888 888     888 888    888   d8P 888{R}
{_G[3]}   888     888 888Y88b 888   888   888Y88888P888 888     888 888         d8P  888{R}
{_G[4]}   888     888 888 Y88b888   888   888 Y888P 888 888     888 888  88888 d88   888{R}
{_G[5]}   888     888 888  Y88888   888   888  Y8P  888 888     888 888    888 8888888888{R}
{_G[6]}   Y88b. .d88P 888   Y8888   888   888   "   888 Y88b. .d88P Y88b  d88P       888{R}
{_G[7]}    "Y88888P"  888    Y888 8888888 888       888  "Y88888P"   "Y8888P88       888{R}
{SEP}
{C.BOLD}{_G[7]} UNIMOG 4.0.0  ·  THE HYBRID AI AGENT  ·  RAG ENHANCED{R}
{SEP}
    """
    safe_print(art, flush=True)

class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        log = {
            "ts": datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
            "level": record.levelname,
            "msg": record.getMessage(),
        }
        if record.exc_info:
            log["exc"] = self.formatException(record.exc_info)
        return json.dumps(log, ensure_ascii=False)

def setup_logger(log_file: Optional[str] = None) -> logging.Logger:
    logger = logging.getLogger("gemini_agent")
    logger.setLevel(logging.DEBUG)
    fmt = JsonFormatter()

    ch = logging.StreamHandler(sys.stdout)
    ch.setFormatter(fmt)
    logger.addHandler(ch)

    if log_file:
        fh = logging.FileHandler(log_file, encoding="utf-8")
        fh.setFormatter(fmt)
        logger.addHandler(fh)

    return logger

log = setup_logger(str(Path(__file__).parent / "gemini_agent.log"))

class TokenBucket:
    """
    Token Bucket レートリミッター（RPM専用モード対応）

    ── RPM 制御: Token Bucket ──────────────────────────────────────
    バケツ容量  = rpm_limit トークン（例: 15）
    補充レート  = rpm_limit トークン / 60秒（例: 毎秒 0.25トークン）
    リクエストごとに 1 トークンを消費。

    ── RPD 制御: 日次カウンタ（オプション）────────────────────────
    rpd_limit=0 を指定すると RPD 無制限モード（Gemma 4 等に対応）。
    通常モデルは rpd_limit > 0 で日次上限を管理。

    ── スレッドセーフ ────────────────────────────────────────────────
    全操作を threading.Lock で保護。
    """

    RPD_UNLIMITED = 0  # RPD無制限を示す定数

    def __init__(self, rpm_limit: int = 15, rpd_limit: int = 1500):
        self.rpm_limit = rpm_limit
        self.rpd_limit = rpd_limit  # 0 = 無制限

        self._tokens: float = float(rpm_limit)
        self._last_refill: float = time.monotonic()
        self._refill_rate: float = rpm_limit / 60.0

        # RPD カウンタ（無制限モードでも記録だけはする）
        self._rpd_count: int = 0
        self._rpd_reset_at: datetime = self._next_utc_midnight()

        self._lock = threading.Lock()

    @staticmethod
    def _next_utc_midnight() -> datetime:
        now = datetime.now(timezone.utc).replace(tzinfo=None)
        return (now + timedelta(days=1)).replace(
            hour=0, minute=0, second=0, microsecond=0
        )

    def _refill(self, now_mono: float):
        elapsed = now_mono - self._last_refill
        self._tokens = min(
            float(self.rpm_limit),
            self._tokens + elapsed * self._refill_rate
        )
        self._last_refill = now_mono

    def _check_rpd_reset(self, now_utc: datetime):
        if now_utc >= self._rpd_reset_at:
            self._rpd_count = 0
            self._rpd_reset_at = self._next_utc_midnight()

    @property
    def rpd_unlimited(self) -> bool:
        return self.rpd_limit == self.RPD_UNLIMITED

    def acquire(self) -> tuple[bool, float]:
        """
        トークンを1枚取得しようとする。

        Returns:
            (True, 0.0)           取得成功
            (False, wait_sec)     RPM 不足 → wait_sec 秒後に再挑戦
            (False, float('inf')) RPD 枯渇 → 今日は使用不可（無制限モード時は発生しない）
        """
        with self._lock:
            now_mono = time.monotonic()
            now_utc  = datetime.now(timezone.utc).replace(tzinfo=None)

            self._check_rpd_reset(now_utc)

            # RPD チェック（無制限モードはスキップ）
            if not self.rpd_unlimited and self._rpd_count >= self.rpd_limit:
                return False, float("inf")

            self._refill(now_mono)

            # 浮動小数点誤差を許容 (1e-5)
            if self._tokens >= 1.0 - 1e-5:
                self._tokens = max(0.0, self._tokens - 1.0)
                self._rpd_count += 1
                return True, 0.0

            wait = (1.0 - self._tokens) / self._refill_rate
            # 微小なジッターを追加してCPUの無駄打ちを防止
            return False, wait + 0.01

    def wait_time(self) -> float:
        with self._lock:
            now_mono = time.monotonic()
            elapsed = now_mono - self._last_refill
            projected = min(
                float(self.rpm_limit),
                self._tokens + elapsed * self._refill_rate
            )
            if projected >= 1.0:
                return 0.0
            return (1.0 - projected) / self._refill_rate

    @property
    def rpd_remaining(self) -> int:
        with self._lock:
            now_utc = datetime.now(timezone.utc).replace(tzinfo=None)
            self._check_rpd_reset(now_utc)
            if self.rpd_unlimited:
                return -1  # -1 = 無制限を示す
            return max(0, self.rpd_limit - self._rpd_count)

    @property
    def tokens_available(self) -> float:
        """現在の利用可能トークン数（表示用）"""
        with self._lock:
            now_mono = time.monotonic()
            elapsed = now_mono - self._last_refill
            return min(
                float(self.rpm_limit),
                self._tokens + elapsed * self._refill_rate
            )


class PipelineTypewriter:
    """
    AIストリーミングを3段パイプラインで表示する:
      Stage1: rawバッファに蓄積（改行 or 200文字超で区切り）
      Stage2: render_markdown でレンダリング（完全行のみ）
      Stage3: タイプライタースレッドが1文字ずつ出力（80文字/秒）
    コードブロックが途中の場合は閉じるまでバッファを保持する。
    auto_mode=True のときは即時出力（遅延なし・レンダリングなし）。
    """
    _CHARS_PER_SEC = 500
    _BUFFER_SIZE   = 200

    def __init__(self, auto_mode: bool = False):
        self._auto_mode = auto_mode
        self._raw_buf   = ""
        self._disp_q: collections.deque = collections.deque()
        self._full: list[str] = []
        self._done  = False
        self._lock  = threading.Lock()
        self._thread: Optional[threading.Thread] = None

    def _should_flush(self, buf: str) -> bool:
        if "\n" not in buf and len(buf) < self._BUFFER_SIZE:
            return False
        if buf.count("```") % 2 != 0:
            return False
        return True

    def _flush_raw(self, force: bool = False):
        if not self._raw_buf:
            return
        last_nl = self._raw_buf.rfind("\n")
        if force or last_nl == -1:
            # finalize 時 or バッファサイズ超過で \n なし: 残り全部を流す（\n は付加しない）
            rendered = render_markdown(self._raw_buf)
            self._disp_q.extend(rendered)
            self._raw_buf = ""
        else:
            # 完全行（最後の \n まで）だけフラッシュ、途中行はバッファに残す
            complete = self._raw_buf[:last_nl + 1]   # 末尾 \n を含む
            self._raw_buf = self._raw_buf[last_nl + 1:]
            rendered = render_markdown(complete)
            if not rendered.endswith("\n"):
                rendered += "\n"
            self._disp_q.extend(rendered)

    def _run(self):
        delay = 1.0 / self._CHARS_PER_SEC
        while not self._done or self._disp_q:
            if self._disp_q:
                sys.stdout.write(self._disp_q.popleft())
                sys.stdout.flush()
                time.sleep(delay)
            else:
                time.sleep(0.002)

    def start(self):
        if self._auto_mode:
            return
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def feed(self, chunk: str):
        if not chunk:
            return
        self._full.append(chunk)
        if self._auto_mode:
            sys.stdout.write(chunk)
            sys.stdout.flush()
            return
        with self._lock:
            self._raw_buf += chunk
            if self._should_flush(self._raw_buf):
                self._flush_raw()

    def finalize(self) -> str:
        full = "".join(self._full)
        if self._auto_mode:
            return full
        with self._lock:
            if self._raw_buf:
                self._flush_raw(force=True)
        self._done = True
        if self._thread and self._thread.is_alive():
            self._thread.join(timeout=60)
        return full


# ── ツール出力メモリキャッシュ ─────────────────────────────────────
_tool_output_cache: dict[str, str] = {}
_tool_cache_counter: int = 0
_TOOL_CHUNK_SIZE: int = 8000
_TOOL_CACHE_MAX_ENTRIES: int = 50
_tool_cache_lock = threading.Lock()

def cache_tool_output(tool_name: str, result: str) -> str:
    """
    ツール出力が _TOOL_CHUNK_SIZE を超える場合はメモリにキャッシュし、
    先頭チャンクと続きの読み方を返す。
    超えない場合はそのまま返す。
    """
    global _tool_cache_counter
    if len(result) <= _TOOL_CHUNK_SIZE:
        return result

    with _tool_cache_lock:
        _tool_cache_counter += 1
        cache_key = f"{tool_name}_{_tool_cache_counter:03d}"
        _tool_output_cache[cache_key] = result
        while len(_tool_output_cache) > _TOOL_CACHE_MAX_ENTRIES:
            del _tool_output_cache[next(iter(_tool_output_cache))]

    total = len(result)
    sliced = result[:_TOOL_CHUNK_SIZE]
    remaining = total - _TOOL_CHUNK_SIZE

    header = f"[{tool_name} の出力  文字 0–{_TOOL_CHUNK_SIZE} / 全{total}文字  cache_key=\"{cache_key}\"]\n{'─' * 60}\n"
    footer = (
        f"\n{'─' * 60}\n"
        f"⚠ 残り {remaining} 文字\n"
        f"  続きを読む: read_tool_cache(cache_key=\"{cache_key}\", offset={_TOOL_CHUNK_SIZE})\n"
        f"{'─' * 60}"
    )
    return header + sliced + footer
